
  //initilize svg or grab svg
  var svg = d3.select("svg");
  var width = svg.attr("width");
  var height = svg.attr("height");
  var color = d3.scaleOrdinal(d3.schemeCategory20b);
 
 
  //intialize data
  var graph = {
    nodes: [
         { name:"KING HENRY IV", size:"7.75193798449612", color:"rgb(205, 92, 92)"},
        { name:"WESTMORELAND", size:"2.32558139534884", color:"rgb(255, 192, 203)"},
        { name:"FALSTAFF", size:"39.0180878552972", color:"rgb(255, 160, 122)"},
        { name:"PRINCE HENRY", size:"43.9276485788114", color:"rgb(139, 0, 0)"},
        { name:"POINS", size:"9.30232558139535", color:"rgb(219, 112, 147)"},
        { name:"EARL OF WORCESTER", size:"8.78552971576227", color:"rgb(255, 165, 0)"},
        { name:"NORTHUMBERLAND", size:"2.84237726098191", color:"rgb(128, 128, 0)"},
        { name:"HOTSPUR", size:"26.0981912144703", color:"rgb(255, 228, 196)"},
        { name:"SIR WALTER BLUNT", size:"2.84237726098191", color:"rgb(144, 238, 144)"},
        { name:"First Carrier", size:"2.0671834625323", color:"rgb(210, 105, 30)"},
        { name:"Ostler", size:"0.258397932816538", color:"rgb(255, 0, 0)"},
        { name:"Second Carrier", size:"1.55038759689922", color:"rgb(220, 20, 60)"},
        { name:"GADSHILL", size:"4.39276485788114", color:"rgb(199, 21, 133)"},
        { name:"Chamberlain", size:"1.55038759689922", color:"rgb(23, 130, 192)"},
        { name:"BARDOLPH", size:"4.65116279069767", color:"rgb(23, 192, 68)"},
        { name:"PETO", size:"1.80878552971576", color:"rgb(192, 74, 23)"},
        { name:"First Traveller", size:"0.258397932816538", color:"rgb(192, 192, 23)"},
        { name:"Thieves", size:"0.258397932816538", color:"rgb(23, 192, 153)"},
        { name:"Travellers", size:"0.516795865633075", color:"rgb(23, 80, 192)"},
        { name:"LADY PERCY", size:"4.1343669250646", color:"rgb(186, 23, 192)"},
        { name:"Servant", size:"0.775193798449612", color:"rgb(238, 128, 242)"},
        { name:"FRANCIS", size:"3.61757105943152", color:"rgb(128, 230, 242)"},
        { name:"Vintner", size:"0.258397932816538", color:"rgb(49, 107, 114)"},
        { name:"Hostess", size:"6.2015503875969", color:"rgb(252, 165, 78)"},
        { name:"Sheriff", size:"1.29198966408269", color:"rgb(78, 252, 130)"},
        { name:"Carrier", size:"0.258397932816538", color:"rgb(136, 78, 252)"},
        { name:"MORTIMER", size:"3.35917312661499", color:"rgb(61, 6, 171)"},
        { name:"GLENDOWER", size:"5.94315245478036", color:"rgb(171, 6, 94)"},
        { name:"EARL OF DOUGLAS", size:"4.90956072351421", color:"rgb(223, 104, 168)"},
        { name:"Messenger", size:"1.55038759689922", color:"rgb(223, 104, 108)"},
        { name:"VERNON", size:"3.61757105943152", color:"rgb(127, 34, 37)"},
        { name:"WORCESTER", size:"0.258397932816538", color:"rgb(247, 15, 23)"},
        { name:"ARCHBISHOP OF YORK", size:"1.29198966408269", color:"rgb(255, 69, 0)"},
        { name:"SIR MICHAEL", size:"1.03359173126615", color:"rgb(139, 69,19)"},
        { name:"LANCASTER", size:"1.29198966408269", color:"rgb(0, 128, 128)"},],
    links: [{source:"KING HENRY IV", target:"WESTMORELAND"},
    {source:"WESTMORELAND", target:"KING HENRY IV"},
    {source:"KING HENRY IV", target:"WESTMORELAND"},
    {source:"WESTMORELAND", target:"KING HENRY IV"},
    {source:"KING HENRY IV", target:"WESTMORELAND"},
    {source:"WESTMORELAND", target:"KING HENRY IV"},
    {source:"KING HENRY IV", target:"WESTMORELAND"},
    {source:"WESTMORELAND", target:"KING HENRY IV"},
    {source:"KING HENRY IV", target:"WESTMORELAND"},
    {source:"WESTMORELAND", target:"FALSTAFF"},
    {source:"FALSTAFF", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"FALSTAFF"},
    {source:"FALSTAFF", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"FALSTAFF"},
    {source:"FALSTAFF", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"FALSTAFF"},
    {source:"FALSTAFF", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"FALSTAFF"},
    {source:"FALSTAFF", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"FALSTAFF"},
    {source:"FALSTAFF", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"FALSTAFF"},
    {source:"FALSTAFF", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"FALSTAFF"},
    {source:"FALSTAFF", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"FALSTAFF"},
    {source:"FALSTAFF", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"FALSTAFF"},
    {source:"FALSTAFF", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"FALSTAFF"},
    {source:"FALSTAFF", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"FALSTAFF"},
    {source:"FALSTAFF", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"FALSTAFF"},
    {source:"FALSTAFF", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"FALSTAFF"},
    {source:"FALSTAFF", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"FALSTAFF"},
    {source:"FALSTAFF", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"FALSTAFF"},
    {source:"FALSTAFF", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"FALSTAFF"},
    {source:"FALSTAFF", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"POINS"},
    {source:"POINS", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"POINS"},
    {source:"POINS", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"POINS"},
    {source:"POINS", target:"FALSTAFF"},
    {source:"FALSTAFF", target:"POINS"},
    {source:"POINS", target:"FALSTAFF"},
    {source:"FALSTAFF", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"FALSTAFF"},
    {source:"FALSTAFF", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"FALSTAFF"},
    {source:"FALSTAFF", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"FALSTAFF"},
    {source:"FALSTAFF", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"POINS"},
    {source:"POINS", target:"FALSTAFF"},
    {source:"FALSTAFF", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"POINS"},
    {source:"POINS", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"POINS"},
    {source:"POINS", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"POINS"},
    {source:"POINS", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"POINS"},
    {source:"POINS", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"POINS"},
    {source:"POINS", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"KING HENRY IV"},
    {source:"KING HENRY IV", target:"EARL OF WORCESTER"},
    {source:"EARL OF WORCESTER", target:"NORTHUMBERLAND"},
    {source:"NORTHUMBERLAND", target:"KING HENRY IV"},
    {source:"KING HENRY IV", target:"NORTHUMBERLAND"},
    {source:"NORTHUMBERLAND", target:"HOTSPUR"},
    {source:"HOTSPUR", target:"SIR WALTER BLUNT"},
    {source:"SIR WALTER BLUNT", target:"KING HENRY IV"},
    {source:"KING HENRY IV", target:"HOTSPUR"},
    {source:"HOTSPUR", target:"KING HENRY IV"},
    {source:"KING HENRY IV", target:"HOTSPUR"},
    {source:"HOTSPUR", target:"NORTHUMBERLAND"},
    {source:"NORTHUMBERLAND", target:"HOTSPUR"},
    {source:"HOTSPUR", target:"NORTHUMBERLAND"},
    {source:"NORTHUMBERLAND", target:"EARL OF WORCESTER"},
    {source:"EARL OF WORCESTER", target:"HOTSPUR"},
    {source:"HOTSPUR", target:"EARL OF WORCESTER"},
    {source:"EARL OF WORCESTER", target:"NORTHUMBERLAND"},
    {source:"NORTHUMBERLAND", target:"EARL OF WORCESTER"},
    {source:"EARL OF WORCESTER", target:"HOTSPUR"},
    {source:"HOTSPUR", target:"NORTHUMBERLAND"},
    {source:"NORTHUMBERLAND", target:"HOTSPUR"},
    {source:"HOTSPUR", target:"EARL OF WORCESTER"},
    {source:"EARL OF WORCESTER", target:"HOTSPUR"},
    {source:"HOTSPUR", target:"NORTHUMBERLAND"},
    {source:"NORTHUMBERLAND", target:"HOTSPUR"},
    {source:"HOTSPUR", target:"EARL OF WORCESTER"},
    {source:"EARL OF WORCESTER", target:"HOTSPUR"},
    {source:"HOTSPUR", target:"EARL OF WORCESTER"},
    {source:"EARL OF WORCESTER", target:"HOTSPUR"},
    {source:"HOTSPUR", target:"EARL OF WORCESTER"},
    {source:"EARL OF WORCESTER", target:"HOTSPUR"},
    {source:"HOTSPUR", target:"EARL OF WORCESTER"},
    {source:"EARL OF WORCESTER", target:"HOTSPUR"},
    {source:"HOTSPUR", target:"EARL OF WORCESTER"},
    {source:"EARL OF WORCESTER", target:"NORTHUMBERLAND"},
    {source:"NORTHUMBERLAND", target:"HOTSPUR"},
    {source:"HOTSPUR", target:"NORTHUMBERLAND"},
    {source:"NORTHUMBERLAND", target:"HOTSPUR"},
    {source:"HOTSPUR", target:"EARL OF WORCESTER"},
    {source:"EARL OF WORCESTER", target:"HOTSPUR"},
    {source:"HOTSPUR", target:"EARL OF WORCESTER"},
    {source:"EARL OF WORCESTER", target:"HOTSPUR"},
    {source:"HOTSPUR", target:"EARL OF WORCESTER"},
    {source:"EARL OF WORCESTER", target:"HOTSPUR"},
    {source:"HOTSPUR", target:"NORTHUMBERLAND"},
    {source:"NORTHUMBERLAND", target:"HOTSPUR"},
    {source:"HOTSPUR", target:"EARL OF WORCESTER"},
    {source:"EARL OF WORCESTER", target:"HOTSPUR"},
    {source:"HOTSPUR", target:"EARL OF WORCESTER"},
    {source:"EARL OF WORCESTER", target:"HOTSPUR"},
    {source:"HOTSPUR", target:"EARL OF WORCESTER"},
    {source:"EARL OF WORCESTER", target:"NORTHUMBERLAND"},
    {source:"NORTHUMBERLAND", target:"HOTSPUR"},
    {source:"HOTSPUR", target:"First Carrier"},
    {source:"First Carrier", target:"Ostler"},
    {source:"Ostler", target:"First Carrier"},
    {source:"First Carrier", target:"Second Carrier"},
    {source:"Second Carrier", target:"First Carrier"},
    {source:"First Carrier", target:"Second Carrier"},
    {source:"Second Carrier", target:"First Carrier"},
    {source:"First Carrier", target:"Second Carrier"},
    {source:"Second Carrier", target:"First Carrier"},
    {source:"First Carrier", target:"Second Carrier"},
    {source:"Second Carrier", target:"First Carrier"},
    {source:"First Carrier", target:"GADSHILL"},
    {source:"GADSHILL", target:"First Carrier"},
    {source:"First Carrier", target:"GADSHILL"},
    {source:"GADSHILL", target:"First Carrier"},
    {source:"First Carrier", target:"GADSHILL"},
    {source:"GADSHILL", target:"Second Carrier"},
    {source:"Second Carrier", target:"GADSHILL"},
    {source:"GADSHILL", target:"Second Carrier"},
    {source:"Second Carrier", target:"GADSHILL"},
    {source:"GADSHILL", target:"Chamberlain"},
    {source:"Chamberlain", target:"GADSHILL"},
    {source:"GADSHILL", target:"Chamberlain"},
    {source:"Chamberlain", target:"GADSHILL"},
    {source:"GADSHILL", target:"Chamberlain"},
    {source:"Chamberlain", target:"GADSHILL"},
    {source:"GADSHILL", target:"Chamberlain"},
    {source:"Chamberlain", target:"GADSHILL"},
    {source:"GADSHILL", target:"Chamberlain"},
    {source:"Chamberlain", target:"GADSHILL"},
    {source:"GADSHILL", target:"Chamberlain"},
    {source:"Chamberlain", target:"GADSHILL"},
    {source:"GADSHILL", target:"POINS"},
    {source:"POINS", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"FALSTAFF"},
    {source:"FALSTAFF", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"FALSTAFF"},
    {source:"FALSTAFF", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"FALSTAFF"},
    {source:"FALSTAFF", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"FALSTAFF"},
    {source:"FALSTAFF", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"FALSTAFF"},
    {source:"FALSTAFF", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"FALSTAFF"},
    {source:"FALSTAFF", target:"GADSHILL"},
    {source:"GADSHILL", target:"FALSTAFF"},
    {source:"FALSTAFF", target:"POINS"},
    {source:"POINS", target:"BARDOLPH"},
    {source:"BARDOLPH", target:"FALSTAFF"},
    {source:"FALSTAFF", target:"GADSHILL"},
    {source:"GADSHILL", target:"FALSTAFF"},
    {source:"FALSTAFF", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"PETO"},
    {source:"PETO", target:"GADSHILL"},
    {source:"GADSHILL", target:"FALSTAFF"},
    {source:"FALSTAFF", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"FALSTAFF"},
    {source:"FALSTAFF", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"POINS"},
    {source:"POINS", target:"FALSTAFF"},
    {source:"FALSTAFF", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"POINS"},
    {source:"POINS", target:"FALSTAFF"},
    {source:"FALSTAFF", target:"First Traveller"},
    {source:"First Traveller", target:"Thieves"},
    {source:"Thieves", target:"Travellers"},
    {source:"Travellers", target:"FALSTAFF"},
    {source:"FALSTAFF", target:"Travellers"},
    {source:"Travellers", target:"FALSTAFF"},
    {source:"FALSTAFF", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"POINS"},
    {source:"POINS", target:"FALSTAFF"},
    {source:"FALSTAFF", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"POINS"},
    {source:"POINS", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"POINS"},
    {source:"POINS", target:"HOTSPUR"},
    {source:"HOTSPUR", target:"LADY PERCY"},
    {source:"LADY PERCY", target:"HOTSPUR"},
    {source:"HOTSPUR", target:"Servant"},
    {source:"Servant", target:"HOTSPUR"},
    {source:"HOTSPUR", target:"Servant"},
    {source:"Servant", target:"HOTSPUR"},
    {source:"HOTSPUR", target:"Servant"},
    {source:"Servant", target:"HOTSPUR"},
    {source:"HOTSPUR", target:"LADY PERCY"},
    {source:"LADY PERCY", target:"HOTSPUR"},
    {source:"HOTSPUR", target:"LADY PERCY"},
    {source:"LADY PERCY", target:"HOTSPUR"},
    {source:"HOTSPUR", target:"LADY PERCY"},
    {source:"LADY PERCY", target:"HOTSPUR"},
    {source:"HOTSPUR", target:"LADY PERCY"},
    {source:"LADY PERCY", target:"HOTSPUR"},
    {source:"HOTSPUR", target:"LADY PERCY"},
    {source:"LADY PERCY", target:"HOTSPUR"},
    {source:"HOTSPUR", target:"LADY PERCY"},
    {source:"LADY PERCY", target:"HOTSPUR"},
    {source:"HOTSPUR", target:"LADY PERCY"},
    {source:"LADY PERCY", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"POINS"},
    {source:"POINS", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"POINS"},
    {source:"POINS", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"POINS"},
    {source:"POINS", target:"FRANCIS"},
    {source:"FRANCIS", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"FRANCIS"},
    {source:"FRANCIS", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"FRANCIS"},
    {source:"FRANCIS", target:"POINS"},
    {source:"POINS", target:"FRANCIS"},
    {source:"FRANCIS", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"FRANCIS"},
    {source:"FRANCIS", target:"POINS"},
    {source:"POINS", target:"FRANCIS"},
    {source:"FRANCIS", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"FRANCIS"},
    {source:"FRANCIS", target:"POINS"},
    {source:"POINS", target:"FRANCIS"},
    {source:"FRANCIS", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"FRANCIS"},
    {source:"FRANCIS", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"POINS"},
    {source:"POINS", target:"FRANCIS"},
    {source:"FRANCIS", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"FRANCIS"},
    {source:"FRANCIS", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"FRANCIS"},
    {source:"FRANCIS", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"FRANCIS"},
    {source:"FRANCIS", target:"POINS"},
    {source:"POINS", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"Vintner"},
    {source:"Vintner", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"POINS"},
    {source:"POINS", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"POINS"},
    {source:"POINS", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"FRANCIS"},
    {source:"FRANCIS", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"POINS"},
    {source:"POINS", target:"FALSTAFF"},
    {source:"FALSTAFF", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"FALSTAFF"},
    {source:"FALSTAFF", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"FALSTAFF"},
    {source:"FALSTAFF", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"FALSTAFF"},
    {source:"FALSTAFF", target:"POINS"},
    {source:"POINS", target:"FALSTAFF"},
    {source:"FALSTAFF", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"FALSTAFF"},
    {source:"FALSTAFF", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"FALSTAFF"},
    {source:"FALSTAFF", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"FALSTAFF"},
    {source:"FALSTAFF", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"FALSTAFF"},
    {source:"FALSTAFF", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"GADSHILL"},
    {source:"GADSHILL", target:"FALSTAFF"},
    {source:"FALSTAFF", target:"GADSHILL"},
    {source:"GADSHILL", target:"PETO"},
    {source:"PETO", target:"FALSTAFF"},
    {source:"FALSTAFF", target:"GADSHILL"},
    {source:"GADSHILL", target:"FALSTAFF"},
    {source:"FALSTAFF", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"FALSTAFF"},
    {source:"FALSTAFF", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"FALSTAFF"},
    {source:"FALSTAFF", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"FALSTAFF"},
    {source:"FALSTAFF", target:"POINS"},
    {source:"POINS", target:"FALSTAFF"},
    {source:"FALSTAFF", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"FALSTAFF"},
    {source:"FALSTAFF", target:"POINS"},
    {source:"POINS", target:"FALSTAFF"},
    {source:"FALSTAFF", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"FALSTAFF"},
    {source:"FALSTAFF", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"FALSTAFF"},
    {source:"FALSTAFF", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"FALSTAFF"},
    {source:"FALSTAFF", target:"POINS"},
    {source:"POINS", target:"FALSTAFF"},
    {source:"FALSTAFF", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"FALSTAFF"},
    {source:"FALSTAFF", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"FALSTAFF"},
    {source:"FALSTAFF", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"POINS"},
    {source:"POINS", target:"FALSTAFF"},
    {source:"FALSTAFF", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"FALSTAFF"},
    {source:"FALSTAFF", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"POINS"},
    {source:"POINS", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"POINS"},
    {source:"POINS", target:"FALSTAFF"},
    {source:"FALSTAFF", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"FALSTAFF"},
    {source:"FALSTAFF", target:"Hostess"},
    {source:"Hostess", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"Hostess"},
    {source:"Hostess", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"FALSTAFF"},
    {source:"FALSTAFF", target:"Hostess"},
    {source:"Hostess", target:"FALSTAFF"},
    {source:"FALSTAFF", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"FALSTAFF"},
    {source:"FALSTAFF", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"BARDOLPH"},
    {source:"BARDOLPH", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"PETO"},
    {source:"PETO", target:"BARDOLPH"},
    {source:"BARDOLPH", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"BARDOLPH"},
    {source:"BARDOLPH", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"BARDOLPH"},
    {source:"BARDOLPH", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"BARDOLPH"},
    {source:"BARDOLPH", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"FALSTAFF"},
    {source:"FALSTAFF", target:"POINS"},
    {source:"POINS", target:"FALSTAFF"},
    {source:"FALSTAFF", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"FALSTAFF"},
    {source:"FALSTAFF", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"FALSTAFF"},
    {source:"FALSTAFF", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"FALSTAFF"},
    {source:"FALSTAFF", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"FALSTAFF"},
    {source:"FALSTAFF", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"FALSTAFF"},
    {source:"FALSTAFF", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"FALSTAFF"},
    {source:"FALSTAFF", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"FALSTAFF"},
    {source:"FALSTAFF", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"FALSTAFF"},
    {source:"FALSTAFF", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"FALSTAFF"},
    {source:"FALSTAFF", target:"Hostess"},
    {source:"Hostess", target:"FALSTAFF"},
    {source:"FALSTAFF", target:"Hostess"},
    {source:"Hostess", target:"FALSTAFF"},
    {source:"FALSTAFF", target:"Hostess"},
    {source:"Hostess", target:"FALSTAFF"},
    {source:"FALSTAFF", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"FALSTAFF"},
    {source:"FALSTAFF", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"FALSTAFF"},
    {source:"FALSTAFF", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"FALSTAFF"},
    {source:"FALSTAFF", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"FALSTAFF"},
    {source:"FALSTAFF", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"FALSTAFF"},
    {source:"FALSTAFF", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"FALSTAFF"},
    {source:"FALSTAFF", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"FALSTAFF"},
    {source:"FALSTAFF", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"FALSTAFF"},
    {source:"FALSTAFF", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"BARDOLPH"},
    {source:"BARDOLPH", target:"FALSTAFF"},
    {source:"FALSTAFF", target:"Hostess"},
    {source:"Hostess", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"Hostess"},
    {source:"Hostess", target:"FALSTAFF"},
    {source:"FALSTAFF", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"FALSTAFF"},
    {source:"FALSTAFF", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"FALSTAFF"},
    {source:"FALSTAFF", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"Sheriff"},
    {source:"Sheriff", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"Sheriff"},
    {source:"Sheriff", target:"Carrier"},
    {source:"Carrier", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"Sheriff"},
    {source:"Sheriff", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"Sheriff"},
    {source:"Sheriff", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"Sheriff"},
    {source:"Sheriff", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"PETO"},
    {source:"PETO", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"PETO"},
    {source:"PETO", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"PETO"},
    {source:"PETO", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"PETO"},
    {source:"PETO", target:"MORTIMER"},
    {source:"MORTIMER", target:"HOTSPUR"},
    {source:"HOTSPUR", target:"GLENDOWER"},
    {source:"GLENDOWER", target:"HOTSPUR"},
    {source:"HOTSPUR", target:"GLENDOWER"},
    {source:"GLENDOWER", target:"HOTSPUR"},
    {source:"HOTSPUR", target:"GLENDOWER"},
    {source:"GLENDOWER", target:"HOTSPUR"},
    {source:"HOTSPUR", target:"GLENDOWER"},
    {source:"GLENDOWER", target:"HOTSPUR"},
    {source:"HOTSPUR", target:"GLENDOWER"},
    {source:"GLENDOWER", target:"HOTSPUR"},
    {source:"HOTSPUR", target:"MORTIMER"},
    {source:"MORTIMER", target:"GLENDOWER"},
    {source:"GLENDOWER", target:"HOTSPUR"},
    {source:"HOTSPUR", target:"GLENDOWER"},
    {source:"GLENDOWER", target:"HOTSPUR"},
    {source:"HOTSPUR", target:"MORTIMER"},
    {source:"MORTIMER", target:"GLENDOWER"},
    {source:"GLENDOWER", target:"HOTSPUR"},
    {source:"HOTSPUR", target:"GLENDOWER"},
    {source:"GLENDOWER", target:"MORTIMER"},
    {source:"MORTIMER", target:"GLENDOWER"},
    {source:"GLENDOWER", target:"HOTSPUR"},
    {source:"HOTSPUR", target:"GLENDOWER"},
    {source:"GLENDOWER", target:"MORTIMER"},
    {source:"MORTIMER", target:"EARL OF WORCESTER"},
    {source:"EARL OF WORCESTER", target:"HOTSPUR"},
    {source:"HOTSPUR", target:"GLENDOWER"},
    {source:"GLENDOWER", target:"HOTSPUR"},
    {source:"HOTSPUR", target:"GLENDOWER"},
    {source:"GLENDOWER", target:"HOTSPUR"},
    {source:"HOTSPUR", target:"GLENDOWER"},
    {source:"GLENDOWER", target:"HOTSPUR"},
    {source:"HOTSPUR", target:"GLENDOWER"},
    {source:"GLENDOWER", target:"HOTSPUR"},
    {source:"HOTSPUR", target:"GLENDOWER"},
    {source:"GLENDOWER", target:"HOTSPUR"},
    {source:"HOTSPUR", target:"GLENDOWER"},
    {source:"GLENDOWER", target:"MORTIMER"},
    {source:"MORTIMER", target:"HOTSPUR"},
    {source:"HOTSPUR", target:"MORTIMER"},
    {source:"MORTIMER", target:"EARL OF WORCESTER"},
    {source:"EARL OF WORCESTER", target:"HOTSPUR"},
    {source:"HOTSPUR", target:"MORTIMER"},
    {source:"MORTIMER", target:"GLENDOWER"},
    {source:"GLENDOWER", target:"MORTIMER"},
    {source:"MORTIMER", target:"GLENDOWER"},
    {source:"GLENDOWER", target:"MORTIMER"},
    {source:"MORTIMER", target:"GLENDOWER"},
    {source:"GLENDOWER", target:"MORTIMER"},
    {source:"MORTIMER", target:"GLENDOWER"},
    {source:"GLENDOWER", target:"MORTIMER"},
    {source:"MORTIMER", target:"GLENDOWER"},
    {source:"GLENDOWER", target:"HOTSPUR"},
    {source:"HOTSPUR", target:"LADY PERCY"},
    {source:"LADY PERCY", target:"HOTSPUR"},
    {source:"HOTSPUR", target:"LADY PERCY"},
    {source:"LADY PERCY", target:"HOTSPUR"},
    {source:"HOTSPUR", target:"LADY PERCY"},
    {source:"LADY PERCY", target:"HOTSPUR"},
    {source:"HOTSPUR", target:"LADY PERCY"},
    {source:"LADY PERCY", target:"HOTSPUR"},
    {source:"HOTSPUR", target:"LADY PERCY"},
    {source:"LADY PERCY", target:"HOTSPUR"},
    {source:"HOTSPUR", target:"LADY PERCY"},
    {source:"LADY PERCY", target:"HOTSPUR"},
    {source:"HOTSPUR", target:"LADY PERCY"},
    {source:"LADY PERCY", target:"HOTSPUR"},
    {source:"HOTSPUR", target:"LADY PERCY"},
    {source:"LADY PERCY", target:"HOTSPUR"},
    {source:"HOTSPUR", target:"GLENDOWER"},
    {source:"GLENDOWER", target:"MORTIMER"},
    {source:"MORTIMER", target:"KING HENRY IV"},
    {source:"KING HENRY IV", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"KING HENRY IV"},
    {source:"KING HENRY IV", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"KING HENRY IV"},
    {source:"KING HENRY IV", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"KING HENRY IV"},
    {source:"KING HENRY IV", target:"SIR WALTER BLUNT"},
    {source:"SIR WALTER BLUNT", target:"KING HENRY IV"},
    {source:"KING HENRY IV", target:"FALSTAFF"},
    {source:"FALSTAFF", target:"BARDOLPH"},
    {source:"BARDOLPH", target:"FALSTAFF"},
    {source:"FALSTAFF", target:"BARDOLPH"},
    {source:"BARDOLPH", target:"FALSTAFF"},
    {source:"FALSTAFF", target:"BARDOLPH"},
    {source:"BARDOLPH", target:"FALSTAFF"},
    {source:"FALSTAFF", target:"BARDOLPH"},
    {source:"BARDOLPH", target:"FALSTAFF"},
    {source:"FALSTAFF", target:"Hostess"},
    {source:"Hostess", target:"FALSTAFF"},
    {source:"FALSTAFF", target:"Hostess"},
    {source:"Hostess", target:"FALSTAFF"},
    {source:"FALSTAFF", target:"Hostess"},
    {source:"Hostess", target:"FALSTAFF"},
    {source:"FALSTAFF", target:"Hostess"},
    {source:"Hostess", target:"FALSTAFF"},
    {source:"FALSTAFF", target:"Hostess"},
    {source:"Hostess", target:"FALSTAFF"},
    {source:"FALSTAFF", target:"Hostess"},
    {source:"Hostess", target:"FALSTAFF"},
    {source:"FALSTAFF", target:"BARDOLPH"},
    {source:"BARDOLPH", target:"Hostess"},
    {source:"Hostess", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"Hostess"},
    {source:"Hostess", target:"FALSTAFF"},
    {source:"FALSTAFF", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"FALSTAFF"},
    {source:"FALSTAFF", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"FALSTAFF"},
    {source:"FALSTAFF", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"Hostess"},
    {source:"Hostess", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"Hostess"},
    {source:"Hostess", target:"FALSTAFF"},
    {source:"FALSTAFF", target:"Hostess"},
    {source:"Hostess", target:"FALSTAFF"},
    {source:"FALSTAFF", target:"Hostess"},
    {source:"Hostess", target:"FALSTAFF"},
    {source:"FALSTAFF", target:"Hostess"},
    {source:"Hostess", target:"FALSTAFF"},
    {source:"FALSTAFF", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"FALSTAFF"},
    {source:"FALSTAFF", target:"Hostess"},
    {source:"Hostess", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"Hostess"},
    {source:"Hostess", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"FALSTAFF"},
    {source:"FALSTAFF", target:"Hostess"},
    {source:"Hostess", target:"FALSTAFF"},
    {source:"FALSTAFF", target:"BARDOLPH"},
    {source:"BARDOLPH", target:"FALSTAFF"},
    {source:"FALSTAFF", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"FALSTAFF"},
    {source:"FALSTAFF", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"FALSTAFF"},
    {source:"FALSTAFF", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"FALSTAFF"},
    {source:"FALSTAFF", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"FALSTAFF"},
    {source:"FALSTAFF", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"FALSTAFF"},
    {source:"FALSTAFF", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"FALSTAFF"},
    {source:"FALSTAFF", target:"BARDOLPH"},
    {source:"BARDOLPH", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"FALSTAFF"},
    {source:"FALSTAFF", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"BARDOLPH"},
    {source:"BARDOLPH", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"FALSTAFF"},
    {source:"FALSTAFF", target:"HOTSPUR"},
    {source:"HOTSPUR", target:"EARL OF DOUGLAS"},
    {source:"EARL OF DOUGLAS", target:"HOTSPUR"},
    {source:"HOTSPUR", target:"Messenger"},
    {source:"Messenger", target:"HOTSPUR"},
    {source:"HOTSPUR", target:"Messenger"},
    {source:"Messenger", target:"HOTSPUR"},
    {source:"HOTSPUR", target:"Messenger"},
    {source:"Messenger", target:"EARL OF WORCESTER"},
    {source:"EARL OF WORCESTER", target:"Messenger"},
    {source:"Messenger", target:"EARL OF WORCESTER"},
    {source:"EARL OF WORCESTER", target:"HOTSPUR"},
    {source:"HOTSPUR", target:"EARL OF WORCESTER"},
    {source:"EARL OF WORCESTER", target:"HOTSPUR"},
    {source:"HOTSPUR", target:"EARL OF DOUGLAS"},
    {source:"EARL OF DOUGLAS", target:"HOTSPUR"},
    {source:"HOTSPUR", target:"EARL OF WORCESTER"},
    {source:"EARL OF WORCESTER", target:"HOTSPUR"},
    {source:"HOTSPUR", target:"EARL OF DOUGLAS"},
    {source:"EARL OF DOUGLAS", target:"HOTSPUR"},
    {source:"HOTSPUR", target:"VERNON"},
    {source:"VERNON", target:"HOTSPUR"},
    {source:"HOTSPUR", target:"VERNON"},
    {source:"VERNON", target:"HOTSPUR"},
    {source:"HOTSPUR", target:"VERNON"},
    {source:"VERNON", target:"HOTSPUR"},
    {source:"HOTSPUR", target:"VERNON"},
    {source:"VERNON", target:"EARL OF DOUGLAS"},
    {source:"EARL OF DOUGLAS", target:"WORCESTER"},
    {source:"WORCESTER", target:"HOTSPUR"},
    {source:"HOTSPUR", target:"VERNON"},
    {source:"VERNON", target:"HOTSPUR"},
    {source:"HOTSPUR", target:"EARL OF DOUGLAS"},
    {source:"EARL OF DOUGLAS", target:"FALSTAFF"},
    {source:"FALSTAFF", target:"BARDOLPH"},
    {source:"BARDOLPH", target:"FALSTAFF"},
    {source:"FALSTAFF", target:"BARDOLPH"},
    {source:"BARDOLPH", target:"FALSTAFF"},
    {source:"FALSTAFF", target:"BARDOLPH"},
    {source:"BARDOLPH", target:"FALSTAFF"},
    {source:"FALSTAFF", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"FALSTAFF"},
    {source:"FALSTAFF", target:"WESTMORELAND"},
    {source:"WESTMORELAND", target:"FALSTAFF"},
    {source:"FALSTAFF", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"FALSTAFF"},
    {source:"FALSTAFF", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"FALSTAFF"},
    {source:"FALSTAFF", target:"WESTMORELAND"},
    {source:"WESTMORELAND", target:"FALSTAFF"},
    {source:"FALSTAFF", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"FALSTAFF"},
    {source:"FALSTAFF", target:"WESTMORELAND"},
    {source:"WESTMORELAND", target:"FALSTAFF"},
    {source:"FALSTAFF", target:"HOTSPUR"},
    {source:"HOTSPUR", target:"EARL OF WORCESTER"},
    {source:"EARL OF WORCESTER", target:"EARL OF DOUGLAS"},
    {source:"EARL OF DOUGLAS", target:"VERNON"},
    {source:"VERNON", target:"HOTSPUR"},
    {source:"HOTSPUR", target:"VERNON"},
    {source:"VERNON", target:"HOTSPUR"},
    {source:"HOTSPUR", target:"EARL OF WORCESTER"},
    {source:"EARL OF WORCESTER", target:"VERNON"},
    {source:"VERNON", target:"EARL OF DOUGLAS"},
    {source:"EARL OF DOUGLAS", target:"VERNON"},
    {source:"VERNON", target:"EARL OF DOUGLAS"},
    {source:"EARL OF DOUGLAS", target:"VERNON"},
    {source:"VERNON", target:"HOTSPUR"},
    {source:"HOTSPUR", target:"VERNON"},
    {source:"VERNON", target:"HOTSPUR"},
    {source:"HOTSPUR", target:"EARL OF WORCESTER"},
    {source:"EARL OF WORCESTER", target:"SIR WALTER BLUNT"},
    {source:"SIR WALTER BLUNT", target:"HOTSPUR"},
    {source:"HOTSPUR", target:"SIR WALTER BLUNT"},
    {source:"SIR WALTER BLUNT", target:"HOTSPUR"},
    {source:"HOTSPUR", target:"SIR WALTER BLUNT"},
    {source:"SIR WALTER BLUNT", target:"HOTSPUR"},
    {source:"HOTSPUR", target:"SIR WALTER BLUNT"},
    {source:"SIR WALTER BLUNT", target:"HOTSPUR"},
    {source:"HOTSPUR", target:"SIR WALTER BLUNT"},
    {source:"SIR WALTER BLUNT", target:"HOTSPUR"},
    {source:"HOTSPUR", target:"SIR WALTER BLUNT"},
    {source:"SIR WALTER BLUNT", target:"ARCHBISHOP OF YORK"},
    {source:"ARCHBISHOP OF YORK", target:"SIR MICHAEL"},
    {source:"SIR MICHAEL", target:"ARCHBISHOP OF YORK"},
    {source:"ARCHBISHOP OF YORK", target:"SIR MICHAEL"},
    {source:"SIR MICHAEL", target:"ARCHBISHOP OF YORK"},
    {source:"ARCHBISHOP OF YORK", target:"SIR MICHAEL"},
    {source:"SIR MICHAEL", target:"ARCHBISHOP OF YORK"},
    {source:"ARCHBISHOP OF YORK", target:"SIR MICHAEL"},
    {source:"SIR MICHAEL", target:"ARCHBISHOP OF YORK"},
    {source:"ARCHBISHOP OF YORK", target:"KING HENRY IV"},
    {source:"KING HENRY IV", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"KING HENRY IV"},
    {source:"KING HENRY IV", target:"EARL OF WORCESTER"},
    {source:"EARL OF WORCESTER", target:"KING HENRY IV"},
    {source:"KING HENRY IV", target:"FALSTAFF"},
    {source:"FALSTAFF", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"EARL OF WORCESTER"},
    {source:"EARL OF WORCESTER", target:"KING HENRY IV"},
    {source:"KING HENRY IV", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"KING HENRY IV"},
    {source:"KING HENRY IV", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"KING HENRY IV"},
    {source:"KING HENRY IV", target:"FALSTAFF"},
    {source:"FALSTAFF", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"FALSTAFF"},
    {source:"FALSTAFF", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"FALSTAFF"},
    {source:"FALSTAFF", target:"EARL OF WORCESTER"},
    {source:"EARL OF WORCESTER", target:"VERNON"},
    {source:"VERNON", target:"EARL OF WORCESTER"},
    {source:"EARL OF WORCESTER", target:"VERNON"},
    {source:"VERNON", target:"HOTSPUR"},
    {source:"HOTSPUR", target:"EARL OF WORCESTER"},
    {source:"EARL OF WORCESTER", target:"EARL OF DOUGLAS"},
    {source:"EARL OF DOUGLAS", target:"HOTSPUR"},
    {source:"HOTSPUR", target:"EARL OF DOUGLAS"},
    {source:"EARL OF DOUGLAS", target:"EARL OF WORCESTER"},
    {source:"EARL OF WORCESTER", target:"HOTSPUR"},
    {source:"HOTSPUR", target:"EARL OF WORCESTER"},
    {source:"EARL OF WORCESTER", target:"EARL OF DOUGLAS"},
    {source:"EARL OF DOUGLAS", target:"EARL OF WORCESTER"},
    {source:"EARL OF WORCESTER", target:"HOTSPUR"},
    {source:"HOTSPUR", target:"VERNON"},
    {source:"VERNON", target:"HOTSPUR"},
    {source:"HOTSPUR", target:"Messenger"},
    {source:"Messenger", target:"HOTSPUR"},
    {source:"HOTSPUR", target:"Messenger"},
    {source:"Messenger", target:"HOTSPUR"},
    {source:"HOTSPUR", target:"SIR WALTER BLUNT"},
    {source:"SIR WALTER BLUNT", target:"EARL OF DOUGLAS"},
    {source:"EARL OF DOUGLAS", target:"SIR WALTER BLUNT"},
    {source:"SIR WALTER BLUNT", target:"EARL OF DOUGLAS"},
    {source:"EARL OF DOUGLAS", target:"SIR WALTER BLUNT"},
    {source:"SIR WALTER BLUNT", target:"HOTSPUR"},
    {source:"HOTSPUR", target:"EARL OF DOUGLAS"},
    {source:"EARL OF DOUGLAS", target:"HOTSPUR"},
    {source:"HOTSPUR", target:"EARL OF DOUGLAS"},
    {source:"EARL OF DOUGLAS", target:"HOTSPUR"},
    {source:"HOTSPUR", target:"EARL OF DOUGLAS"},
    {source:"EARL OF DOUGLAS", target:"HOTSPUR"},
    {source:"HOTSPUR", target:"EARL OF DOUGLAS"},
    {source:"EARL OF DOUGLAS", target:"HOTSPUR"},
    {source:"HOTSPUR", target:"FALSTAFF"},
    {source:"FALSTAFF", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"FALSTAFF"},
    {source:"FALSTAFF", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"FALSTAFF"},
    {source:"FALSTAFF", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"FALSTAFF"},
    {source:"FALSTAFF", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"FALSTAFF"},
    {source:"FALSTAFF", target:"KING HENRY IV"},
    {source:"KING HENRY IV", target:"LANCASTER"},
    {source:"LANCASTER", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"KING HENRY IV"},
    {source:"KING HENRY IV", target:"WESTMORELAND"},
    {source:"WESTMORELAND", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"LANCASTER"},
    {source:"LANCASTER", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"KING HENRY IV"},
    {source:"KING HENRY IV", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"EARL OF DOUGLAS"},
    {source:"EARL OF DOUGLAS", target:"KING HENRY IV"},
    {source:"KING HENRY IV", target:"EARL OF DOUGLAS"},
    {source:"EARL OF DOUGLAS", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"KING HENRY IV"},
    {source:"KING HENRY IV", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"KING HENRY IV"},
    {source:"KING HENRY IV", target:"HOTSPUR"},
    {source:"HOTSPUR", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"HOTSPUR"},
    {source:"HOTSPUR", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"HOTSPUR"},
    {source:"HOTSPUR", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"HOTSPUR"},
    {source:"HOTSPUR", target:"FALSTAFF"},
    {source:"FALSTAFF", target:"HOTSPUR"},
    {source:"HOTSPUR", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"FALSTAFF"},
    {source:"FALSTAFF", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"LANCASTER"},
    {source:"LANCASTER", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"FALSTAFF"},
    {source:"FALSTAFF", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"FALSTAFF"},
    {source:"FALSTAFF", target:"LANCASTER"},
    {source:"LANCASTER", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"FALSTAFF"},
    {source:"FALSTAFF", target:"KING HENRY IV"},
    {source:"KING HENRY IV", target:"EARL OF WORCESTER"},
    {source:"EARL OF WORCESTER", target:"KING HENRY IV"},
    {source:"KING HENRY IV", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"KING HENRY IV"},
    {source:"KING HENRY IV", target:"PRINCE HENRY"},
    {source:"PRINCE HENRY", target:"LANCASTER"},
    {source:"LANCASTER", target:"KING HENRY IV"},
    {source:"KING HENRY IV", target:"LANCASTER"},]
  };
// var myColor =d3.scaleOrdinal().domain(node)
// .range(["red","blue","red","blue","red","blue","red","blue","red","blue","red","blue","red","blue","red","blue"])

  var simulation = d3
    .forceSimulation(graph.nodes)
    .force(
      "link",
      d3
        .forceLink()
        .id(function(d) {
          return d.name;
        })
        .links(graph.links)
    )
    .force("gravity",gravity(-1000))
  

    .force("charge", d3.forceManyBody().strength(-500))
    .force("center", d3.forceCenter(width / 2, height / 2))
    .on("tick", ticked);

  var link = svg
    .append("g")
    .attr("class", "links")
    .selectAll("line")
    .data(graph.links)
    .enter()
    .append("line")
    .attr("stroke-width", function(d) {
      return 3;
    });
    var drag = 
      d3
        .drag()
        .on("start", dragstarted)
        .on("drag", dragged)
        .on("end", dragended);


var textandnode = svg
  .append("g")
  .selectAll("g")
  .data(graph.nodes)
  .enter()
  .append("g")
  .call(drag)
  ;

var circles = textandnode
.append("circle")
.attr("r", (d)=>d.size)
//.attr("r", "20")
//.attr("fill", function(d){
  //return color(d.group);
//})
.attr("fill", (d)=>d.color)
;

var texts = textandnode
.append("text")
.text(function(d){return d.name});

  // var node = svg
  //   .append("g")
  //   .attr("class", "nodes")
  //   .selectAll("circle")
  //   .data(graph.nodes)
  //   .enter()
  //   .append("circle")
  //   .attr("r", 10)
  //   .attr("fill", "red");

    // var drag = 
    //   d3
    //     .drag()
    //     .on("start", dragstarted)
    //     .on("drag", dragged)
    //     .on("end", dragended);
//node.call(drag);
  

 
  // nodes.append("text")
  // .text(function(d){
  //   return d.name;
  // })
  // .style("fill","#000")
  // .style("font-size", "20px")
  // .attr("x",6)
  // .attr("y",3);

// simulation.force(
//   'link',
//   d3.forceLink().id((link)=>link.id)
//   .strength((link)=>link.strength)
// );
// const linkElements = svg
// .append('g')
// .selectAll('line')
// .data(links)
// .enter()
// .append('line')
// .attr('stroke-width',1)
// .attr('stroke','#E5E5E5')
// .attr('x1',(link) => link.source.x)
// .attr('y1',(link) => link.source.y)
// .attr('x2',(link) => link.target.x)
// .attr('y2',(link) => link.target.y);

//simulation.force('link').link(links);
  function ticked() {
    textandnode.attr("transform", function(d){
      return "translate("+d.x+","+d.y+")";
    });
    link
      .attr("x1", function(d) {
        return d.source.x;
      })
      .attr("y1", function(d) {
        return d.source.y;
      })
      .attr("x2", function(d) {
        return d.target.x;
      })
      .attr("y2", function(d) {
        return d.target.y;
      });
    
  //   node
  //     .attr("cx", function(d) {
  //       return d.x;
  //     })
  //     .attr("cy", function(d) {
  //       return d.y;
  //     });
  // 
}

  function dragstarted(d) {
    if (!d3.event.active) simulation.alphaTarget(0.3).restart();
    d.fx = d.x;
    d.fy = d.y;
  }

  function dragged(d) {
    d.fx = d3.event.x;
    d.fy = d3.event.y;
  }

  function dragended(d) {
    if (!d3.event.active) simulation.alphaTarget(0);
    d.fx = null;
    d.fy = null;
  }
 function gravity(alpha){
  return function(d){
    d.y+=(d.cy -d.y)*alpha;
    d.x +=(d.cx-d.x)*alpha;
  };
 }
 


