
  //initilize svg or grab svg
  var svg = d3.select("svg");
  var width = svg.attr("width");
  var height = svg.attr("height");
  var color = d3.scaleOrdinal(d3.schemeCategory20b);
 
 
  //intialize data
  var graph = {
    nodes: [
      { name:"YORK", size:"37", color:"rgb(0,4,163)"},
{ name:"EDWARD", size:"34", color:"rgb(26,1,239)"},
{ name:"MONTAGUE", size:"15", color:"rgb(95,188,86)"},
{ name:"RICHARD", size:"42", color:"rgb(4,216,220)"},
{ name:"NORFOLK", size:"3", color:"rgb(107,248,25)"},
{ name:"WARWICK", size:"98", color:"rgb(100,86,136)"},
{ name:"KING HENRY VI", size:"71", color:"rgb(162,97,0)"},
{ name:"NORTHUMBERLAND", size:"15", color:"rgb(145,158,46)"},
{ name:"CLIFFORD", size:"35", color:"rgb(54,204,213)"},
{ name:"WESTMORELAND", size:"6", color:"rgb(0,91,167)"},
{ name:"EXETER", size:"13", color:"rgb(121,26,155)"},
{ name:"QUEEN MARGARET", size:"53", color:"rgb(144,53,21)"},
{ name:"PRINCE EDWARD", size:"15", color:"rgb(229,114,138)"},
{ name:"Messenger", size:"6", color:"rgb(6,234,122)"},
{ name:"JOHN MORTIMER", size:"1", color:"rgb(187,14,203)"},
{ name:"RUTLAND", size:"7", color:"rgb(122,48,236)"},
{ name:"Tutor", size:"2", color:"rgb(104,220,144)"},
{ name:"PRINCE", size:"1", color:"rgb(68,64,88)"},
{ name:"GEORGE", size:"6", color:"rgb(114,253,151)"},
{ name:"Son", size:"4", color:"rgb(201,27,255)"},
{ name:"Father", size:"4", color:"rgb(48,212,21)"},
{ name:"First Keeper", size:"7", color:"rgb(189,81,75)"},
{ name:"Second Keeper", size:"9", color:"rgb(86,195,231)"},
{ name:"KING EDWARD IV", size:"98", color:"rgb(114,0,41)"},
{ name:"GLOUCESTER", size:"66", color:"rgb(157,189,165)"},
{ name:"CLARENCE", size:"33", color:"rgb(91,53,28)"},
{ name:"LADY GREY", size:"24", color:"rgb(169,114,40)"},
{ name:"Nobleman", size:"1", color:"rgb(173,195,28)"},
{ name:"KING LEWIS XI", size:"21", color:"rgb(79,223,184)"},
{ name:"OXFORD", size:"13", color:"rgb(124,171,221)"},
{ name:"BONA", size:"4", color:"rgb(164,161,206)"},
{ name:"Post", size:"9", color:"rgb(157,211,95)"},
{ name:"SOMERSET", size:"14", color:"rgb(83,226,5)"},
{ name:"HASTINGS", size:"9", color:"rgb(60,90,159)"},
{ name:"QUEEN ELIZABETH", size:"7", color:"rgb(54,245,158)"},
{ name:"First Watchman", size:"5", color:"rgb(13,183,226)"},
{ name:"Second Watchman", size:"5", color:"rgb(23,196,123)"},
{ name:"Third Watchman", size:"3", color:"rgb(132,233,9)"},
{ name:"RIVERS", size:"5", color:"rgb(149,48,144)"},
{ name:"Huntsman", size:"2", color:"rgb(252,132,102)"},
{ name:"Lieutenant", size:"1", color:"rgb(114,160,47)"},
{ name:"Mayor", size:"3", color:"rgb(246,100,20)"},
{ name:"Soldier", size:"1", color:"rgb(220,235,61)"},
{ name:"All", size:"1", color:"rgb(90,235,124)"},
{ name:"First Messenger", size:"1", color:"rgb(134,103,39)"},
{ name:"Second Messenger", size:"1", color:"rgb(230,74,217)"}],
    links: [{source:"YORK", target:"EDWARD"},
    {source:"EDWARD", target:"MONTAGUE"},
    {source:"MONTAGUE", target:"RICHARD"},
    {source:"RICHARD", target:"YORK"},
    {source:"YORK", target:"NORFOLK"},
    {source:"NORFOLK", target:"RICHARD"},
    {source:"RICHARD", target:"WARWICK"},
    {source:"WARWICK", target:"YORK"},
    {source:"YORK", target:"NORFOLK"},
    {source:"NORFOLK", target:"YORK"},
    {source:"YORK", target:"WARWICK"},
    {source:"WARWICK", target:"YORK"},
    {source:"YORK", target:"RICHARD"},
    {source:"RICHARD", target:"WARWICK"},
    {source:"WARWICK", target:"YORK"},
    {source:"YORK", target:"WARWICK"},
    {source:"WARWICK", target:"KING HENRY VI"},
    {source:"KING HENRY VI", target:"NORTHUMBERLAND"},
    {source:"NORTHUMBERLAND", target:"CLIFFORD"},
    {source:"CLIFFORD", target:"WESTMORELAND"},
    {source:"WESTMORELAND", target:"KING HENRY VI"},
    {source:"KING HENRY VI", target:"CLIFFORD"},
    {source:"CLIFFORD", target:"NORTHUMBERLAND"},
    {source:"NORTHUMBERLAND", target:"KING HENRY VI"},
    {source:"KING HENRY VI", target:"EXETER"},
    {source:"EXETER", target:"KING HENRY VI"},
    {source:"KING HENRY VI", target:"YORK"},
    {source:"YORK", target:"EXETER"},
    {source:"EXETER", target:"YORK"},
    {source:"YORK", target:"EXETER"},
    {source:"EXETER", target:"WARWICK"},
    {source:"WARWICK", target:"CLIFFORD"},
    {source:"CLIFFORD", target:"WARWICK"},
    {source:"WARWICK", target:"KING HENRY VI"},
    {source:"KING HENRY VI", target:"YORK"},
    {source:"YORK", target:"WARWICK"},
    {source:"WARWICK", target:"WESTMORELAND"},
    {source:"WESTMORELAND", target:"WARWICK"},
    {source:"WARWICK", target:"NORTHUMBERLAND"},
    {source:"NORTHUMBERLAND", target:"WESTMORELAND"},
    {source:"WESTMORELAND", target:"CLIFFORD"},
    {source:"CLIFFORD", target:"WARWICK"},
    {source:"WARWICK", target:"YORK"},
    {source:"YORK", target:"KING HENRY VI"},
    {source:"KING HENRY VI", target:"WARWICK"},
    {source:"WARWICK", target:"KING HENRY VI"},
    {source:"KING HENRY VI", target:"RICHARD"},
    {source:"RICHARD", target:"EDWARD"},
    {source:"EDWARD", target:"MONTAGUE"},
    {source:"MONTAGUE", target:"RICHARD"},
    {source:"RICHARD", target:"YORK"},
    {source:"YORK", target:"KING HENRY VI"},
    {source:"KING HENRY VI", target:"WARWICK"},
    {source:"WARWICK", target:"KING HENRY VI"},
    {source:"KING HENRY VI", target:"WARWICK"},
    {source:"WARWICK", target:"KING HENRY VI"},
    {source:"KING HENRY VI", target:"YORK"},
    {source:"YORK", target:"KING HENRY VI"},
    {source:"KING HENRY VI", target:"YORK"},
    {source:"YORK", target:"KING HENRY VI"},
    {source:"KING HENRY VI", target:"YORK"},
    {source:"YORK", target:"WARWICK"},
    {source:"WARWICK", target:"EXETER"},
    {source:"EXETER", target:"KING HENRY VI"},
    {source:"KING HENRY VI", target:"EXETER"},
    {source:"EXETER", target:"YORK"},
    {source:"YORK", target:"EXETER"},
    {source:"EXETER", target:"KING HENRY VI"},
    {source:"KING HENRY VI", target:"NORTHUMBERLAND"},
    {source:"NORTHUMBERLAND", target:"WARWICK"},
    {source:"WARWICK", target:"NORTHUMBERLAND"},
    {source:"NORTHUMBERLAND", target:"CLIFFORD"},
    {source:"CLIFFORD", target:"KING HENRY VI"},
    {source:"KING HENRY VI", target:"YORK"},
    {source:"YORK", target:"WARWICK"},
    {source:"WARWICK", target:"KING HENRY VI"},
    {source:"KING HENRY VI", target:"YORK"},
    {source:"YORK", target:"KING HENRY VI"},
    {source:"KING HENRY VI", target:"CLIFFORD"},
    {source:"CLIFFORD", target:"WARWICK"},
    {source:"WARWICK", target:"WESTMORELAND"},
    {source:"WESTMORELAND", target:"CLIFFORD"},
    {source:"CLIFFORD", target:"WESTMORELAND"},
    {source:"WESTMORELAND", target:"NORTHUMBERLAND"},
    {source:"NORTHUMBERLAND", target:"CLIFFORD"},
    {source:"CLIFFORD", target:"WESTMORELAND"},
    {source:"WESTMORELAND", target:"NORTHUMBERLAND"},
    {source:"NORTHUMBERLAND", target:"CLIFFORD"},
    {source:"CLIFFORD", target:"WARWICK"},
    {source:"WARWICK", target:"EXETER"},
    {source:"EXETER", target:"KING HENRY VI"},
    {source:"KING HENRY VI", target:"WARWICK"},
    {source:"WARWICK", target:"KING HENRY VI"},
    {source:"KING HENRY VI", target:"YORK"},
    {source:"YORK", target:"WARWICK"},
    {source:"WARWICK", target:"KING HENRY VI"},
    {source:"KING HENRY VI", target:"YORK"},
    {source:"YORK", target:"EXETER"},
    {source:"EXETER", target:"YORK"},
    {source:"YORK", target:"WARWICK"},
    {source:"WARWICK", target:"NORFOLK"},
    {source:"NORFOLK", target:"MONTAGUE"},
    {source:"MONTAGUE", target:"KING HENRY VI"},
    {source:"KING HENRY VI", target:"EXETER"},
    {source:"EXETER", target:"KING HENRY VI"},
    {source:"KING HENRY VI", target:"QUEEN MARGARET"},
    {source:"QUEEN MARGARET", target:"KING HENRY VI"},
    {source:"KING HENRY VI", target:"QUEEN MARGARET"},
    {source:"QUEEN MARGARET", target:"PRINCE EDWARD"},
    {source:"PRINCE EDWARD", target:"KING HENRY VI"},
    {source:"KING HENRY VI", target:"QUEEN MARGARET"},
    {source:"QUEEN MARGARET", target:"KING HENRY VI"},
    {source:"KING HENRY VI", target:"QUEEN MARGARET"},
    {source:"QUEEN MARGARET", target:"KING HENRY VI"},
    {source:"KING HENRY VI", target:"QUEEN MARGARET"},
    {source:"QUEEN MARGARET", target:"PRINCE EDWARD"},
    {source:"PRINCE EDWARD", target:"QUEEN MARGARET"},
    {source:"QUEEN MARGARET", target:"KING HENRY VI"},
    {source:"KING HENRY VI", target:"EXETER"},
    {source:"EXETER", target:"RICHARD"},
    {source:"RICHARD", target:"EDWARD"},
    {source:"EDWARD", target:"MONTAGUE"},
    {source:"MONTAGUE", target:"YORK"},
    {source:"YORK", target:"EDWARD"},
    {source:"EDWARD", target:"YORK"},
    {source:"YORK", target:"RICHARD"},
    {source:"RICHARD", target:"YORK"},
    {source:"YORK", target:"RICHARD"},
    {source:"RICHARD", target:"EDWARD"},
    {source:"EDWARD", target:"YORK"},
    {source:"YORK", target:"EDWARD"},
    {source:"EDWARD", target:"RICHARD"},
    {source:"RICHARD", target:"YORK"},
    {source:"YORK", target:"RICHARD"},
    {source:"RICHARD", target:"YORK"},
    {source:"YORK", target:"RICHARD"},
    {source:"RICHARD", target:"YORK"},
    {source:"YORK", target:"Messenger"},
    {source:"Messenger", target:"YORK"},
    {source:"YORK", target:"MONTAGUE"},
    {source:"MONTAGUE", target:"JOHN MORTIMER"},
    {source:"JOHN MORTIMER", target:"YORK"},
    {source:"YORK", target:"RICHARD"},
    {source:"RICHARD", target:"EDWARD"},
    {source:"EDWARD", target:"YORK"},
    {source:"YORK", target:"RUTLAND"},
    {source:"RUTLAND", target:"CLIFFORD"},
    {source:"CLIFFORD", target:"Tutor"},
    {source:"Tutor", target:"CLIFFORD"},
    {source:"CLIFFORD", target:"Tutor"},
    {source:"Tutor", target:"CLIFFORD"},
    {source:"CLIFFORD", target:"RUTLAND"},
    {source:"RUTLAND", target:"CLIFFORD"},
    {source:"CLIFFORD", target:"RUTLAND"},
    {source:"RUTLAND", target:"CLIFFORD"},
    {source:"CLIFFORD", target:"RUTLAND"},
    {source:"RUTLAND", target:"CLIFFORD"},
    {source:"CLIFFORD", target:"RUTLAND"},
    {source:"RUTLAND", target:"CLIFFORD"},
    {source:"CLIFFORD", target:"RUTLAND"},
    {source:"RUTLAND", target:"CLIFFORD"},
    {source:"CLIFFORD", target:"RUTLAND"},
    {source:"RUTLAND", target:"CLIFFORD"},
    {source:"CLIFFORD", target:"YORK"},
    {source:"YORK", target:"NORTHUMBERLAND"},
    {source:"NORTHUMBERLAND", target:"CLIFFORD"},
    {source:"CLIFFORD", target:"YORK"},
    {source:"YORK", target:"CLIFFORD"},
    {source:"CLIFFORD", target:"YORK"},
    {source:"YORK", target:"CLIFFORD"},
    {source:"CLIFFORD", target:"QUEEN MARGARET"},
    {source:"QUEEN MARGARET", target:"NORTHUMBERLAND"},
    {source:"NORTHUMBERLAND", target:"CLIFFORD"},
    {source:"CLIFFORD", target:"NORTHUMBERLAND"},
    {source:"NORTHUMBERLAND", target:"YORK"},
    {source:"YORK", target:"NORTHUMBERLAND"},
    {source:"NORTHUMBERLAND", target:"QUEEN MARGARET"},
    {source:"QUEEN MARGARET", target:"CLIFFORD"},
    {source:"CLIFFORD", target:"QUEEN MARGARET"},
    {source:"QUEEN MARGARET", target:"YORK"},
    {source:"YORK", target:"NORTHUMBERLAND"},
    {source:"NORTHUMBERLAND", target:"YORK"},
    {source:"YORK", target:"NORTHUMBERLAND"},
    {source:"NORTHUMBERLAND", target:"QUEEN MARGARET"},
    {source:"QUEEN MARGARET", target:"CLIFFORD"},
    {source:"CLIFFORD", target:"QUEEN MARGARET"},
    {source:"QUEEN MARGARET", target:"YORK"},
    {source:"YORK", target:"QUEEN MARGARET"},
    {source:"QUEEN MARGARET", target:"EDWARD"},
    {source:"EDWARD", target:"RICHARD"},
    {source:"RICHARD", target:"EDWARD"},
    {source:"EDWARD", target:"RICHARD"},
    {source:"RICHARD", target:"EDWARD"},
    {source:"EDWARD", target:"RICHARD"},
    {source:"RICHARD", target:"Messenger"},
    {source:"Messenger", target:"EDWARD"},
    {source:"EDWARD", target:"RICHARD"},
    {source:"RICHARD", target:"Messenger"},
    {source:"Messenger", target:"EDWARD"},
    {source:"EDWARD", target:"RICHARD"},
    {source:"RICHARD", target:"EDWARD"},
    {source:"EDWARD", target:"RICHARD"},
    {source:"RICHARD", target:"WARWICK"},
    {source:"WARWICK", target:"RICHARD"},
    {source:"RICHARD", target:"EDWARD"},
    {source:"EDWARD", target:"WARWICK"},
    {source:"WARWICK", target:"EDWARD"},
    {source:"EDWARD", target:"WARWICK"},
    {source:"WARWICK", target:"RICHARD"},
    {source:"RICHARD", target:"WARWICK"},
    {source:"WARWICK", target:"RICHARD"},
    {source:"RICHARD", target:"WARWICK"},
    {source:"WARWICK", target:"RICHARD"},
    {source:"RICHARD", target:"EDWARD"},
    {source:"EDWARD", target:"WARWICK"},
    {source:"WARWICK", target:"RICHARD"},
    {source:"RICHARD", target:"EDWARD"},
    {source:"EDWARD", target:"WARWICK"},
    {source:"WARWICK", target:"Messenger"},
    {source:"Messenger", target:"WARWICK"},
    {source:"WARWICK", target:"QUEEN MARGARET"},
    {source:"QUEEN MARGARET", target:"KING HENRY VI"},
    {source:"KING HENRY VI", target:"CLIFFORD"},
    {source:"CLIFFORD", target:"KING HENRY VI"},
    {source:"KING HENRY VI", target:"QUEEN MARGARET"},
    {source:"QUEEN MARGARET", target:"KING HENRY VI"},
    {source:"KING HENRY VI", target:"PRINCE"},
    {source:"PRINCE", target:"CLIFFORD"},
    {source:"CLIFFORD", target:"Messenger"},
    {source:"Messenger", target:"CLIFFORD"},
    {source:"CLIFFORD", target:"QUEEN MARGARET"},
    {source:"QUEEN MARGARET", target:"KING HENRY VI"},
    {source:"KING HENRY VI", target:"NORTHUMBERLAND"},
    {source:"NORTHUMBERLAND", target:"PRINCE EDWARD"},
    {source:"PRINCE EDWARD", target:"EDWARD"},
    {source:"EDWARD", target:"QUEEN MARGARET"},
    {source:"QUEEN MARGARET", target:"EDWARD"},
    {source:"EDWARD", target:"CLIFFORD"},
    {source:"CLIFFORD", target:"RICHARD"},
    {source:"RICHARD", target:"CLIFFORD"},
    {source:"CLIFFORD", target:"RICHARD"},
    {source:"RICHARD", target:"CLIFFORD"},
    {source:"CLIFFORD", target:"RICHARD"},
    {source:"RICHARD", target:"WARWICK"},
    {source:"WARWICK", target:"QUEEN MARGARET"},
    {source:"QUEEN MARGARET", target:"WARWICK"},
    {source:"WARWICK", target:"CLIFFORD"},
    {source:"CLIFFORD", target:"WARWICK"},
    {source:"WARWICK", target:"NORTHUMBERLAND"},
    {source:"NORTHUMBERLAND", target:"RICHARD"},
    {source:"RICHARD", target:"CLIFFORD"},
    {source:"CLIFFORD", target:"RICHARD"},
    {source:"RICHARD", target:"KING HENRY VI"},
    {source:"KING HENRY VI", target:"QUEEN MARGARET"},
    {source:"QUEEN MARGARET", target:"KING HENRY VI"},
    {source:"KING HENRY VI", target:"CLIFFORD"},
    {source:"CLIFFORD", target:"RICHARD"},
    {source:"RICHARD", target:"EDWARD"},
    {source:"EDWARD", target:"WARWICK"},
    {source:"WARWICK", target:"PRINCE EDWARD"},
    {source:"PRINCE EDWARD", target:"RICHARD"},
    {source:"RICHARD", target:"QUEEN MARGARET"},
    {source:"QUEEN MARGARET", target:"RICHARD"},
    {source:"RICHARD", target:"EDWARD"},
    {source:"EDWARD", target:"GEORGE"},
    {source:"GEORGE", target:"EDWARD"},
    {source:"EDWARD", target:"QUEEN MARGARET"},
    {source:"QUEEN MARGARET", target:"EDWARD"},
    {source:"EDWARD", target:"WARWICK"},
    {source:"WARWICK", target:"EDWARD"},
    {source:"EDWARD", target:"WARWICK"},
    {source:"WARWICK", target:"GEORGE"},
    {source:"GEORGE", target:"EDWARD"},
    {source:"EDWARD", target:"RICHARD"},
    {source:"RICHARD", target:"WARWICK"},
    {source:"WARWICK", target:"EDWARD"},
    {source:"EDWARD", target:"RICHARD"},
    {source:"RICHARD", target:"WARWICK"},
    {source:"WARWICK", target:"GEORGE"},
    {source:"GEORGE", target:"RICHARD"},
    {source:"RICHARD", target:"CLIFFORD"},
    {source:"CLIFFORD", target:"RICHARD"},
    {source:"RICHARD", target:"KING HENRY VI"},
    {source:"KING HENRY VI", target:"Son"},
    {source:"Son", target:"KING HENRY VI"},
    {source:"KING HENRY VI", target:"Father"},
    {source:"Father", target:"KING HENRY VI"},
    {source:"KING HENRY VI", target:"Son"},
    {source:"Son", target:"Father"},
    {source:"Father", target:"KING HENRY VI"},
    {source:"KING HENRY VI", target:"Son"},
    {source:"Son", target:"Father"},
    {source:"Father", target:"KING HENRY VI"},
    {source:"KING HENRY VI", target:"Son"},
    {source:"Son", target:"Father"},
    {source:"Father", target:"KING HENRY VI"},
    {source:"KING HENRY VI", target:"PRINCE EDWARD"},
    {source:"PRINCE EDWARD", target:"QUEEN MARGARET"},
    {source:"QUEEN MARGARET", target:"EXETER"},
    {source:"EXETER", target:"KING HENRY VI"},
    {source:"KING HENRY VI", target:"CLIFFORD"},
    {source:"CLIFFORD", target:"EDWARD"},
    {source:"EDWARD", target:"WARWICK"},
    {source:"WARWICK", target:"EDWARD"},
    {source:"EDWARD", target:"RICHARD"},
    {source:"RICHARD", target:"EDWARD"},
    {source:"EDWARD", target:"RICHARD"},
    {source:"RICHARD", target:"WARWICK"},
    {source:"WARWICK", target:"EDWARD"},
    {source:"EDWARD", target:"WARWICK"},
    {source:"WARWICK", target:"RICHARD"},
    {source:"RICHARD", target:"GEORGE"},
    {source:"GEORGE", target:"RICHARD"},
    {source:"RICHARD", target:"EDWARD"},
    {source:"EDWARD", target:"WARWICK"},
    {source:"WARWICK", target:"GEORGE"},
    {source:"GEORGE", target:"RICHARD"},
    {source:"RICHARD", target:"EDWARD"},
    {source:"EDWARD", target:"GEORGE"},
    {source:"GEORGE", target:"WARWICK"},
    {source:"WARWICK", target:"RICHARD"},
    {source:"RICHARD", target:"WARWICK"},
    {source:"WARWICK", target:"EDWARD"},
    {source:"EDWARD", target:"RICHARD"},
    {source:"RICHARD", target:"WARWICK"},
    {source:"WARWICK", target:"First Keeper"},
    {source:"First Keeper", target:"Second Keeper"},
    {source:"Second Keeper", target:"First Keeper"},
    {source:"First Keeper", target:"Second Keeper"},
    {source:"Second Keeper", target:"KING HENRY VI"},
    {source:"KING HENRY VI", target:"First Keeper"},
    {source:"First Keeper", target:"KING HENRY VI"},
    {source:"KING HENRY VI", target:"Second Keeper"},
    {source:"Second Keeper", target:"First Keeper"},
    {source:"First Keeper", target:"KING HENRY VI"},
    {source:"KING HENRY VI", target:"Second Keeper"},
    {source:"Second Keeper", target:"KING HENRY VI"},
    {source:"KING HENRY VI", target:"Second Keeper"},
    {source:"Second Keeper", target:"KING HENRY VI"},
    {source:"KING HENRY VI", target:"Second Keeper"},
    {source:"Second Keeper", target:"KING HENRY VI"},
    {source:"KING HENRY VI", target:"Second Keeper"},
    {source:"Second Keeper", target:"KING HENRY VI"},
    {source:"KING HENRY VI", target:"Second Keeper"},
    {source:"Second Keeper", target:"KING HENRY VI"},
    {source:"KING HENRY VI", target:"Second Keeper"},
    {source:"Second Keeper", target:"KING HENRY VI"},
    {source:"KING HENRY VI", target:"First Keeper"},
    {source:"First Keeper", target:"KING HENRY VI"},
    {source:"KING HENRY VI", target:"First Keeper"},
    {source:"First Keeper", target:"KING HENRY VI"},
    {source:"KING HENRY VI", target:"First Keeper"},
    {source:"First Keeper", target:"KING HENRY VI"},
    {source:"KING HENRY VI", target:"KING EDWARD IV"},
    {source:"KING EDWARD IV", target:"GLOUCESTER"},
    {source:"GLOUCESTER", target:"KING EDWARD IV"},
    {source:"KING EDWARD IV", target:"GLOUCESTER"},
    {source:"GLOUCESTER", target:"CLARENCE"},
    {source:"CLARENCE", target:"GLOUCESTER"},
    {source:"GLOUCESTER", target:"KING EDWARD IV"},
    {source:"KING EDWARD IV", target:"LADY GREY"},
    {source:"LADY GREY", target:"GLOUCESTER"},
    {source:"GLOUCESTER", target:"CLARENCE"},
    {source:"CLARENCE", target:"GLOUCESTER"},
    {source:"GLOUCESTER", target:"KING EDWARD IV"},
    {source:"KING EDWARD IV", target:"CLARENCE"},
    {source:"CLARENCE", target:"GLOUCESTER"},
    {source:"GLOUCESTER", target:"LADY GREY"},
    {source:"LADY GREY", target:"GLOUCESTER"},
    {source:"GLOUCESTER", target:"KING EDWARD IV"},
    {source:"KING EDWARD IV", target:"LADY GREY"},
    {source:"LADY GREY", target:"KING EDWARD IV"},
    {source:"KING EDWARD IV", target:"GLOUCESTER"},
    {source:"GLOUCESTER", target:"KING EDWARD IV"},
    {source:"KING EDWARD IV", target:"LADY GREY"},
    {source:"LADY GREY", target:"KING EDWARD IV"},
    {source:"KING EDWARD IV", target:"LADY GREY"},
    {source:"LADY GREY", target:"KING EDWARD IV"},
    {source:"KING EDWARD IV", target:"LADY GREY"},
    {source:"LADY GREY", target:"KING EDWARD IV"},
    {source:"KING EDWARD IV", target:"LADY GREY"},
    {source:"LADY GREY", target:"KING EDWARD IV"},
    {source:"KING EDWARD IV", target:"LADY GREY"},
    {source:"LADY GREY", target:"KING EDWARD IV"},
    {source:"KING EDWARD IV", target:"LADY GREY"},
    {source:"LADY GREY", target:"KING EDWARD IV"},
    {source:"KING EDWARD IV", target:"LADY GREY"},
    {source:"LADY GREY", target:"GLOUCESTER"},
    {source:"GLOUCESTER", target:"CLARENCE"},
    {source:"CLARENCE", target:"LADY GREY"},
    {source:"LADY GREY", target:"KING EDWARD IV"},
    {source:"KING EDWARD IV", target:"LADY GREY"},
    {source:"LADY GREY", target:"KING EDWARD IV"},
    {source:"KING EDWARD IV", target:"LADY GREY"},
    {source:"LADY GREY", target:"GLOUCESTER"},
    {source:"GLOUCESTER", target:"KING EDWARD IV"},
    {source:"KING EDWARD IV", target:"LADY GREY"},
    {source:"LADY GREY", target:"KING EDWARD IV"},
    {source:"KING EDWARD IV", target:"LADY GREY"},
    {source:"LADY GREY", target:"KING EDWARD IV"},
    {source:"KING EDWARD IV", target:"LADY GREY"},
    {source:"LADY GREY", target:"KING EDWARD IV"},
    {source:"KING EDWARD IV", target:"LADY GREY"},
    {source:"LADY GREY", target:"KING EDWARD IV"},
    {source:"KING EDWARD IV", target:"LADY GREY"},
    {source:"LADY GREY", target:"KING EDWARD IV"},
    {source:"KING EDWARD IV", target:"LADY GREY"},
    {source:"LADY GREY", target:"KING EDWARD IV"},
    {source:"KING EDWARD IV", target:"LADY GREY"},
    {source:"LADY GREY", target:"KING EDWARD IV"},
    {source:"KING EDWARD IV", target:"LADY GREY"},
    {source:"LADY GREY", target:"GLOUCESTER"},
    {source:"GLOUCESTER", target:"CLARENCE"},
    {source:"CLARENCE", target:"KING EDWARD IV"},
    {source:"KING EDWARD IV", target:"LADY GREY"},
    {source:"LADY GREY", target:"KING EDWARD IV"},
    {source:"KING EDWARD IV", target:"LADY GREY"},
    {source:"LADY GREY", target:"KING EDWARD IV"},
    {source:"KING EDWARD IV", target:"LADY GREY"},
    {source:"LADY GREY", target:"KING EDWARD IV"},
    {source:"KING EDWARD IV", target:"GLOUCESTER"},
    {source:"GLOUCESTER", target:"CLARENCE"},
    {source:"CLARENCE", target:"KING EDWARD IV"},
    {source:"KING EDWARD IV", target:"GLOUCESTER"},
    {source:"GLOUCESTER", target:"KING EDWARD IV"},
    {source:"KING EDWARD IV", target:"CLARENCE"},
    {source:"CLARENCE", target:"KING EDWARD IV"},
    {source:"KING EDWARD IV", target:"GLOUCESTER"},
    {source:"GLOUCESTER", target:"CLARENCE"},
    {source:"CLARENCE", target:"GLOUCESTER"},
    {source:"GLOUCESTER", target:"KING EDWARD IV"},
    {source:"KING EDWARD IV", target:"Nobleman"},
    {source:"Nobleman", target:"KING EDWARD IV"},
    {source:"KING EDWARD IV", target:"GLOUCESTER"},
    {source:"GLOUCESTER", target:"KING LEWIS XI"},
    {source:"KING LEWIS XI", target:"QUEEN MARGARET"},
    {source:"QUEEN MARGARET", target:"KING LEWIS XI"},
    {source:"KING LEWIS XI", target:"QUEEN MARGARET"},
    {source:"QUEEN MARGARET", target:"KING LEWIS XI"},
    {source:"KING LEWIS XI", target:"QUEEN MARGARET"},
    {source:"QUEEN MARGARET", target:"KING LEWIS XI"},
    {source:"KING LEWIS XI", target:"QUEEN MARGARET"},
    {source:"QUEEN MARGARET", target:"KING LEWIS XI"},
    {source:"KING LEWIS XI", target:"QUEEN MARGARET"},
    {source:"QUEEN MARGARET", target:"KING LEWIS XI"},
    {source:"KING LEWIS XI", target:"QUEEN MARGARET"},
    {source:"QUEEN MARGARET", target:"KING LEWIS XI"},
    {source:"KING LEWIS XI", target:"QUEEN MARGARET"},
    {source:"QUEEN MARGARET", target:"WARWICK"},
    {source:"WARWICK", target:"QUEEN MARGARET"},
    {source:"QUEEN MARGARET", target:"WARWICK"},
    {source:"WARWICK", target:"QUEEN MARGARET"},
    {source:"QUEEN MARGARET", target:"WARWICK"},
    {source:"WARWICK", target:"PRINCE EDWARD"},
    {source:"PRINCE EDWARD", target:"WARWICK"},
    {source:"WARWICK", target:"OXFORD"},
    {source:"OXFORD", target:"WARWICK"},
    {source:"WARWICK", target:"OXFORD"},
    {source:"OXFORD", target:"WARWICK"},
    {source:"WARWICK", target:"OXFORD"},
    {source:"OXFORD", target:"WARWICK"},
    {source:"WARWICK", target:"KING LEWIS XI"},
    {source:"KING LEWIS XI", target:"QUEEN MARGARET"},
    {source:"QUEEN MARGARET", target:"KING LEWIS XI"},
    {source:"KING LEWIS XI", target:"WARWICK"},
    {source:"WARWICK", target:"KING LEWIS XI"},
    {source:"KING LEWIS XI", target:"WARWICK"},
    {source:"WARWICK", target:"KING LEWIS XI"},
    {source:"KING LEWIS XI", target:"WARWICK"},
    {source:"WARWICK", target:"KING LEWIS XI"},
    {source:"KING LEWIS XI", target:"BONA"},
    {source:"BONA", target:"KING LEWIS XI"},
    {source:"KING LEWIS XI", target:"PRINCE EDWARD"},
    {source:"PRINCE EDWARD", target:"QUEEN MARGARET"},
    {source:"QUEEN MARGARET", target:"KING LEWIS XI"},
    {source:"KING LEWIS XI", target:"WARWICK"},
    {source:"WARWICK", target:"QUEEN MARGARET"},
    {source:"QUEEN MARGARET", target:"KING LEWIS XI"},
    {source:"KING LEWIS XI", target:"Post"},
    {source:"Post", target:"OXFORD"},
    {source:"OXFORD", target:"PRINCE EDWARD"},
    {source:"PRINCE EDWARD", target:"KING LEWIS XI"},
    {source:"KING LEWIS XI", target:"QUEEN MARGARET"},
    {source:"QUEEN MARGARET", target:"WARWICK"},
    {source:"WARWICK", target:"KING LEWIS XI"},
    {source:"KING LEWIS XI", target:"QUEEN MARGARET"},
    {source:"QUEEN MARGARET", target:"WARWICK"},
    {source:"WARWICK", target:"QUEEN MARGARET"},
    {source:"QUEEN MARGARET", target:"WARWICK"},
    {source:"WARWICK", target:"BONA"},
    {source:"BONA", target:"QUEEN MARGARET"},
    {source:"QUEEN MARGARET", target:"BONA"},
    {source:"BONA", target:"WARWICK"},
    {source:"WARWICK", target:"KING LEWIS XI"},
    {source:"KING LEWIS XI", target:"QUEEN MARGARET"},
    {source:"QUEEN MARGARET", target:"KING LEWIS XI"},
    {source:"KING LEWIS XI", target:"BONA"},
    {source:"BONA", target:"QUEEN MARGARET"},
    {source:"QUEEN MARGARET", target:"WARWICK"},
    {source:"WARWICK", target:"KING LEWIS XI"},
    {source:"KING LEWIS XI", target:"WARWICK"},
    {source:"WARWICK", target:"QUEEN MARGARET"},
    {source:"QUEEN MARGARET", target:"PRINCE EDWARD"},
    {source:"PRINCE EDWARD", target:"KING LEWIS XI"},
    {source:"KING LEWIS XI", target:"WARWICK"},
    {source:"WARWICK", target:"GLOUCESTER"},
    {source:"GLOUCESTER", target:"CLARENCE"},
    {source:"CLARENCE", target:"SOMERSET"},
    {source:"SOMERSET", target:"GLOUCESTER"},
    {source:"GLOUCESTER", target:"CLARENCE"},
    {source:"CLARENCE", target:"KING EDWARD IV"},
    {source:"KING EDWARD IV", target:"CLARENCE"},
    {source:"CLARENCE", target:"KING EDWARD IV"},
    {source:"KING EDWARD IV", target:"GLOUCESTER"},
    {source:"GLOUCESTER", target:"KING EDWARD IV"},
    {source:"KING EDWARD IV", target:"GLOUCESTER"},
    {source:"GLOUCESTER", target:"KING EDWARD IV"},
    {source:"KING EDWARD IV", target:"CLARENCE"},
    {source:"CLARENCE", target:"GLOUCESTER"},
    {source:"GLOUCESTER", target:"KING EDWARD IV"},
    {source:"KING EDWARD IV", target:"MONTAGUE"},
    {source:"MONTAGUE", target:"HASTINGS"},
    {source:"HASTINGS", target:"MONTAGUE"},
    {source:"MONTAGUE", target:"HASTINGS"},
    {source:"HASTINGS", target:"CLARENCE"},
    {source:"CLARENCE", target:"KING EDWARD IV"},
    {source:"KING EDWARD IV", target:"GLOUCESTER"},
    {source:"GLOUCESTER", target:"CLARENCE"},
    {source:"CLARENCE", target:"KING EDWARD IV"},
    {source:"KING EDWARD IV", target:"CLARENCE"},
    {source:"CLARENCE", target:"KING EDWARD IV"},
    {source:"KING EDWARD IV", target:"QUEEN ELIZABETH"},
    {source:"QUEEN ELIZABETH", target:"KING EDWARD IV"},
    {source:"KING EDWARD IV", target:"GLOUCESTER"},
    {source:"GLOUCESTER", target:"KING EDWARD IV"},
    {source:"KING EDWARD IV", target:"Post"},
    {source:"Post", target:"KING EDWARD IV"},
    {source:"KING EDWARD IV", target:"Post"},
    {source:"Post", target:"KING EDWARD IV"},
    {source:"KING EDWARD IV", target:"Post"},
    {source:"Post", target:"KING EDWARD IV"},
    {source:"KING EDWARD IV", target:"Post"},
    {source:"Post", target:"KING EDWARD IV"},
    {source:"KING EDWARD IV", target:"Post"},
    {source:"Post", target:"KING EDWARD IV"},
    {source:"KING EDWARD IV", target:"Post"},
    {source:"Post", target:"CLARENCE"},
    {source:"CLARENCE", target:"GLOUCESTER"},
    {source:"GLOUCESTER", target:"KING EDWARD IV"},
    {source:"KING EDWARD IV", target:"MONTAGUE"},
    {source:"MONTAGUE", target:"HASTINGS"},
    {source:"HASTINGS", target:"KING EDWARD IV"},
    {source:"KING EDWARD IV", target:"GLOUCESTER"},
    {source:"GLOUCESTER", target:"KING EDWARD IV"},
    {source:"KING EDWARD IV", target:"WARWICK"},
    {source:"WARWICK", target:"CLARENCE"},
    {source:"CLARENCE", target:"WARWICK"},
    {source:"WARWICK", target:"First Watchman"},
    {source:"First Watchman", target:"Second Watchman"},
    {source:"Second Watchman", target:"First Watchman"},
    {source:"First Watchman", target:"Second Watchman"},
    {source:"Second Watchman", target:"Third Watchman"},
    {source:"Third Watchman", target:"First Watchman"},
    {source:"First Watchman", target:"Third Watchman"},
    {source:"Third Watchman", target:"Second Watchman"},
    {source:"Second Watchman", target:"Third Watchman"},
    {source:"Third Watchman", target:"First Watchman"},
    {source:"First Watchman", target:"Second Watchman"},
    {source:"Second Watchman", target:"WARWICK"},
    {source:"WARWICK", target:"First Watchman"},
    {source:"First Watchman", target:"Second Watchman"},
    {source:"Second Watchman", target:"SOMERSET"},
    {source:"SOMERSET", target:"WARWICK"},
    {source:"WARWICK", target:"KING EDWARD IV"},
    {source:"KING EDWARD IV", target:"WARWICK"},
    {source:"WARWICK", target:"KING EDWARD IV"},
    {source:"KING EDWARD IV", target:"WARWICK"},
    {source:"WARWICK", target:"KING EDWARD IV"},
    {source:"KING EDWARD IV", target:"OXFORD"},
    {source:"OXFORD", target:"WARWICK"},
    {source:"WARWICK", target:"RIVERS"},
    {source:"RIVERS", target:"QUEEN ELIZABETH"},
    {source:"QUEEN ELIZABETH", target:"RIVERS"},
    {source:"RIVERS", target:"QUEEN ELIZABETH"},
    {source:"QUEEN ELIZABETH", target:"RIVERS"},
    {source:"RIVERS", target:"QUEEN ELIZABETH"},
    {source:"QUEEN ELIZABETH", target:"RIVERS"},
    {source:"RIVERS", target:"QUEEN ELIZABETH"},
    {source:"QUEEN ELIZABETH", target:"RIVERS"},
    {source:"RIVERS", target:"QUEEN ELIZABETH"},
    {source:"QUEEN ELIZABETH", target:"GLOUCESTER"},
    {source:"GLOUCESTER", target:"Huntsman"},
    {source:"Huntsman", target:"KING EDWARD IV"},
    {source:"KING EDWARD IV", target:"GLOUCESTER"},
    {source:"GLOUCESTER", target:"KING EDWARD IV"},
    {source:"KING EDWARD IV", target:"HASTINGS"},
    {source:"HASTINGS", target:"GLOUCESTER"},
    {source:"GLOUCESTER", target:"KING EDWARD IV"},
    {source:"KING EDWARD IV", target:"GLOUCESTER"},
    {source:"GLOUCESTER", target:"KING EDWARD IV"},
    {source:"KING EDWARD IV", target:"Huntsman"},
    {source:"Huntsman", target:"GLOUCESTER"},
    {source:"GLOUCESTER", target:"KING EDWARD IV"},
    {source:"KING EDWARD IV", target:"KING HENRY VI"},
    {source:"KING HENRY VI", target:"Lieutenant"},
    {source:"Lieutenant", target:"KING HENRY VI"},
    {source:"KING HENRY VI", target:"WARWICK"},
    {source:"WARWICK", target:"CLARENCE"},
    {source:"CLARENCE", target:"WARWICK"},
    {source:"WARWICK", target:"KING HENRY VI"},
    {source:"KING HENRY VI", target:"WARWICK"},
    {source:"WARWICK", target:"CLARENCE"},
    {source:"CLARENCE", target:"WARWICK"},
    {source:"WARWICK", target:"CLARENCE"},
    {source:"CLARENCE", target:"WARWICK"},
    {source:"WARWICK", target:"KING HENRY VI"},
    {source:"KING HENRY VI", target:"CLARENCE"},
    {source:"CLARENCE", target:"KING HENRY VI"},
    {source:"KING HENRY VI", target:"SOMERSET"},
    {source:"SOMERSET", target:"KING HENRY VI"},
    {source:"KING HENRY VI", target:"WARWICK"},
    {source:"WARWICK", target:"Post"},
    {source:"Post", target:"WARWICK"},
    {source:"WARWICK", target:"Post"},
    {source:"Post", target:"WARWICK"},
    {source:"WARWICK", target:"SOMERSET"},
    {source:"SOMERSET", target:"OXFORD"},
    {source:"OXFORD", target:"SOMERSET"},
    {source:"SOMERSET", target:"KING EDWARD IV"},
    {source:"KING EDWARD IV", target:"GLOUCESTER"},
    {source:"GLOUCESTER", target:"KING EDWARD IV"},
    {source:"KING EDWARD IV", target:"HASTINGS"},
    {source:"HASTINGS", target:"Mayor"},
    {source:"Mayor", target:"KING EDWARD IV"},
    {source:"KING EDWARD IV", target:"Mayor"},
    {source:"Mayor", target:"KING EDWARD IV"},
    {source:"KING EDWARD IV", target:"GLOUCESTER"},
    {source:"GLOUCESTER", target:"HASTINGS"},
    {source:"HASTINGS", target:"Mayor"},
    {source:"Mayor", target:"GLOUCESTER"},
    {source:"GLOUCESTER", target:"HASTINGS"},
    {source:"HASTINGS", target:"KING EDWARD IV"},
    {source:"KING EDWARD IV", target:"GLOUCESTER"},
    {source:"GLOUCESTER", target:"KING EDWARD IV"},
    {source:"KING EDWARD IV", target:"MONTAGUE"},
    {source:"MONTAGUE", target:"KING EDWARD IV"},
    {source:"KING EDWARD IV", target:"MONTAGUE"},
    {source:"MONTAGUE", target:"KING EDWARD IV"},
    {source:"KING EDWARD IV", target:"MONTAGUE"},
    {source:"MONTAGUE", target:"GLOUCESTER"},
    {source:"GLOUCESTER", target:"KING EDWARD IV"},
    {source:"KING EDWARD IV", target:"HASTINGS"},
    {source:"HASTINGS", target:"GLOUCESTER"},
    {source:"GLOUCESTER", target:"KING EDWARD IV"},
    {source:"KING EDWARD IV", target:"MONTAGUE"},
    {source:"MONTAGUE", target:"HASTINGS"},
    {source:"HASTINGS", target:"Soldier"},
    {source:"Soldier", target:"MONTAGUE"},
    {source:"MONTAGUE", target:"All"},
    {source:"All", target:"KING EDWARD IV"},
    {source:"KING EDWARD IV", target:"WARWICK"},
    {source:"WARWICK", target:"KING HENRY VI"},
    {source:"KING HENRY VI", target:"CLARENCE"},
    {source:"CLARENCE", target:"WARWICK"},
    {source:"WARWICK", target:"KING HENRY VI"},
    {source:"KING HENRY VI", target:"CLARENCE"},
    {source:"CLARENCE", target:"KING HENRY VI"},
    {source:"KING HENRY VI", target:"MONTAGUE"},
    {source:"MONTAGUE", target:"OXFORD"},
    {source:"OXFORD", target:"KING HENRY VI"},
    {source:"KING HENRY VI", target:"WARWICK"},
    {source:"WARWICK", target:"KING HENRY VI"},
    {source:"KING HENRY VI", target:"EXETER"},
    {source:"EXETER", target:"KING HENRY VI"},
    {source:"KING HENRY VI", target:"EXETER"},
    {source:"EXETER", target:"KING EDWARD IV"},
    {source:"KING EDWARD IV", target:"GLOUCESTER"},
    {source:"GLOUCESTER", target:"WARWICK"},
    {source:"WARWICK", target:"First Messenger"},
    {source:"First Messenger", target:"WARWICK"},
    {source:"WARWICK", target:"Second Messenger"},
    {source:"Second Messenger", target:"WARWICK"},
    {source:"WARWICK", target:"SOMERSET"},
    {source:"SOMERSET", target:"WARWICK"},
    {source:"WARWICK", target:"SOMERSET"},
    {source:"SOMERSET", target:"WARWICK"},
    {source:"WARWICK", target:"SOMERSET"},
    {source:"SOMERSET", target:"KING EDWARD IV"},
    {source:"KING EDWARD IV", target:"GLOUCESTER"},
    {source:"GLOUCESTER", target:"WARWICK"},
    {source:"WARWICK", target:"KING EDWARD IV"},
    {source:"KING EDWARD IV", target:"WARWICK"},
    {source:"WARWICK", target:"GLOUCESTER"},
    {source:"GLOUCESTER", target:"WARWICK"},
    {source:"WARWICK", target:"GLOUCESTER"},
    {source:"GLOUCESTER", target:"WARWICK"},
    {source:"WARWICK", target:"KING EDWARD IV"},
    {source:"KING EDWARD IV", target:"WARWICK"},
    {source:"WARWICK", target:"KING EDWARD IV"},
    {source:"KING EDWARD IV", target:"GLOUCESTER"},
    {source:"GLOUCESTER", target:"EDWARD"},
    {source:"EDWARD", target:"GLOUCESTER"},
    {source:"GLOUCESTER", target:"WARWICK"},
    {source:"WARWICK", target:"KING EDWARD IV"},
    {source:"KING EDWARD IV", target:"WARWICK"},
    {source:"WARWICK", target:"OXFORD"},
    {source:"OXFORD", target:"GLOUCESTER"},
    {source:"GLOUCESTER", target:"KING EDWARD IV"},
    {source:"KING EDWARD IV", target:"WARWICK"},
    {source:"WARWICK", target:"MONTAGUE"},
    {source:"MONTAGUE", target:"GLOUCESTER"},
    {source:"GLOUCESTER", target:"KING EDWARD IV"},
    {source:"KING EDWARD IV", target:"SOMERSET"},
    {source:"SOMERSET", target:"GLOUCESTER"},
    {source:"GLOUCESTER", target:"WARWICK"},
    {source:"WARWICK", target:"CLARENCE"},
    {source:"CLARENCE", target:"KING EDWARD IV"},
    {source:"KING EDWARD IV", target:"GLOUCESTER"},
    {source:"GLOUCESTER", target:"WARWICK"},
    {source:"WARWICK", target:"KING EDWARD IV"},
    {source:"KING EDWARD IV", target:"WARWICK"},
    {source:"WARWICK", target:"KING EDWARD IV"},
    {source:"KING EDWARD IV", target:"WARWICK"},
    {source:"WARWICK", target:"SOMERSET"},
    {source:"SOMERSET", target:"WARWICK"},
    {source:"WARWICK", target:"SOMERSET"},
    {source:"SOMERSET", target:"WARWICK"},
    {source:"WARWICK", target:"OXFORD"},
    {source:"OXFORD", target:"KING EDWARD IV"},
    {source:"KING EDWARD IV", target:"CLARENCE"},
    {source:"CLARENCE", target:"GLOUCESTER"},
    {source:"GLOUCESTER", target:"KING EDWARD IV"},
    {source:"KING EDWARD IV", target:"QUEEN MARGARET"},
    {source:"QUEEN MARGARET", target:"PRINCE EDWARD"},
    {source:"PRINCE EDWARD", target:"OXFORD"},
    {source:"OXFORD", target:"SOMERSET"},
    {source:"SOMERSET", target:"QUEEN MARGARET"},
    {source:"QUEEN MARGARET", target:"PRINCE EDWARD"},
    {source:"PRINCE EDWARD", target:"Messenger"},
    {source:"Messenger", target:"OXFORD"},
    {source:"OXFORD", target:"SOMERSET"},
    {source:"SOMERSET", target:"QUEEN MARGARET"},
    {source:"QUEEN MARGARET", target:"OXFORD"},
    {source:"OXFORD", target:"KING EDWARD IV"},
    {source:"KING EDWARD IV", target:"QUEEN MARGARET"},
    {source:"QUEEN MARGARET", target:"KING EDWARD IV"},
    {source:"KING EDWARD IV", target:"OXFORD"},
    {source:"OXFORD", target:"SOMERSET"},
    {source:"SOMERSET", target:"QUEEN MARGARET"},
    {source:"QUEEN MARGARET", target:"KING EDWARD IV"},
    {source:"KING EDWARD IV", target:"GLOUCESTER"},
    {source:"GLOUCESTER", target:"KING EDWARD IV"},
    {source:"KING EDWARD IV", target:"PRINCE EDWARD"},
    {source:"PRINCE EDWARD", target:"QUEEN MARGARET"},
    {source:"QUEEN MARGARET", target:"GLOUCESTER"},
    {source:"GLOUCESTER", target:"PRINCE EDWARD"},
    {source:"PRINCE EDWARD", target:"GLOUCESTER"},
    {source:"GLOUCESTER", target:"QUEEN MARGARET"},
    {source:"QUEEN MARGARET", target:"GLOUCESTER"},
    {source:"GLOUCESTER", target:"PRINCE EDWARD"},
    {source:"PRINCE EDWARD", target:"KING EDWARD IV"},
    {source:"KING EDWARD IV", target:"CLARENCE"},
    {source:"CLARENCE", target:"PRINCE EDWARD"},
    {source:"PRINCE EDWARD", target:"KING EDWARD IV"},
    {source:"KING EDWARD IV", target:"GLOUCESTER"},
    {source:"GLOUCESTER", target:"CLARENCE"},
    {source:"CLARENCE", target:"QUEEN MARGARET"},
    {source:"QUEEN MARGARET", target:"GLOUCESTER"},
    {source:"GLOUCESTER", target:"KING EDWARD IV"},
    {source:"KING EDWARD IV", target:"GLOUCESTER"},
    {source:"GLOUCESTER", target:"KING EDWARD IV"},
    {source:"KING EDWARD IV", target:"GLOUCESTER"},
    {source:"GLOUCESTER", target:"CLARENCE"},
    {source:"CLARENCE", target:"GLOUCESTER"},
    {source:"GLOUCESTER", target:"QUEEN MARGARET"},
    {source:"QUEEN MARGARET", target:"KING EDWARD IV"},
    {source:"KING EDWARD IV", target:"QUEEN MARGARET"},
    {source:"QUEEN MARGARET", target:"CLARENCE"},
    {source:"CLARENCE", target:"QUEEN MARGARET"},
    {source:"QUEEN MARGARET", target:"CLARENCE"},
    {source:"CLARENCE", target:"QUEEN MARGARET"},
    {source:"QUEEN MARGARET", target:"KING EDWARD IV"},
    {source:"KING EDWARD IV", target:"QUEEN MARGARET"},
    {source:"QUEEN MARGARET", target:"KING EDWARD IV"},
    {source:"KING EDWARD IV", target:"CLARENCE"},
    {source:"CLARENCE", target:"KING EDWARD IV"},
    {source:"KING EDWARD IV", target:"GLOUCESTER"},
    {source:"GLOUCESTER", target:"KING HENRY VI"},
    {source:"KING HENRY VI", target:"GLOUCESTER"},
    {source:"GLOUCESTER", target:"KING HENRY VI"},
    {source:"KING HENRY VI", target:"GLOUCESTER"},
    {source:"GLOUCESTER", target:"KING HENRY VI"},
    {source:"KING HENRY VI", target:"GLOUCESTER"},
    {source:"GLOUCESTER", target:"KING HENRY VI"},
    {source:"KING HENRY VI", target:"GLOUCESTER"},
    {source:"GLOUCESTER", target:"KING HENRY VI"},
    {source:"KING HENRY VI", target:"GLOUCESTER"},
    {source:"GLOUCESTER", target:"KING HENRY VI"},
    {source:"KING HENRY VI", target:"GLOUCESTER"},
    {source:"GLOUCESTER", target:"KING HENRY VI"},
    {source:"KING HENRY VI", target:"GLOUCESTER"},
    {source:"GLOUCESTER", target:"KING EDWARD IV"},
    {source:"KING EDWARD IV", target:"GLOUCESTER"},
    {source:"GLOUCESTER", target:"KING EDWARD IV"},
    {source:"KING EDWARD IV", target:"CLARENCE"},
    {source:"CLARENCE", target:"QUEEN ELIZABETH"},
    {source:"QUEEN ELIZABETH", target:"GLOUCESTER"},
    {source:"GLOUCESTER", target:"KING EDWARD IV"},
    {source:"KING EDWARD IV", target:"CLARENCE"},
    {source:"CLARENCE", target:"KING EDWARD IV"},
    {source:"KING EDWARD IV", target:"COUNTESS"}]
  };
// var myColor =d3.scaleOrdinal().domain(node)
// .range(["red","blue","red","blue","red","blue","red","blue","red","blue","red","blue","red","blue","red","blue"])

  var simulation = d3
    .forceSimulation(graph.nodes)
    .force(
      "link",
      d3
        .forceLink()
        .id(function(d) {
          return d.name;
        })
        .links(graph.links)
    )
    .force("gravity",gravity(-1000))
  

    .force("charge", d3.forceManyBody().strength(-500))
    .force("center", d3.forceCenter(width / 2, height / 2))
    .on("tick", ticked);

  var link = svg
    .append("g")
    .attr("class", "links")
    .selectAll("line")
    .data(graph.links)
    .enter()
    .append("line")
    .attr("stroke-width", function(d) {
      return 3;
    });
    var drag = 
      d3
        .drag()
        .on("start", dragstarted)
        .on("drag", dragged)
        .on("end", dragended);


var textandnode = svg
  .append("g")
  .selectAll("g")
  .data(graph.nodes)
  .enter()
  .append("g")
  .call(drag)
  ;

var circles = textandnode
.append("circle")
.attr("r", (d)=>d.size)
//.attr("r", "20")
//.attr("fill", function(d){
  //return color(d.group);
//})
.attr("fill", (d)=>d.color)
;

var texts = textandnode
.append("text")
.text(function(d){return d.name});

  // var node = svg
  //   .append("g")
  //   .attr("class", "nodes")
  //   .selectAll("circle")
  //   .data(graph.nodes)
  //   .enter()
  //   .append("circle")
  //   .attr("r", 10)
  //   .attr("fill", "red");

    // var drag = 
    //   d3
    //     .drag()
    //     .on("start", dragstarted)
    //     .on("drag", dragged)
    //     .on("end", dragended);
//node.call(drag);
  

 
  // nodes.append("text")
  // .text(function(d){
  //   return d.name;
  // })
  // .style("fill","#000")
  // .style("font-size", "20px")
  // .attr("x",6)
  // .attr("y",3);

// simulation.force(
//   'link',
//   d3.forceLink().id((link)=>link.id)
//   .strength((link)=>link.strength)
// );
// const linkElements = svg
// .append('g')
// .selectAll('line')
// .data(links)
// .enter()
// .append('line')
// .attr('stroke-width',1)
// .attr('stroke','#E5E5E5')
// .attr('x1',(link) => link.source.x)
// .attr('y1',(link) => link.source.y)
// .attr('x2',(link) => link.target.x)
// .attr('y2',(link) => link.target.y);

//simulation.force('link').link(links);
  function ticked() {
    textandnode.attr("transform", function(d){
      return "translate("+d.x+","+d.y+")";
    });
    link
      .attr("x1", function(d) {
        return d.source.x;
      })
      .attr("y1", function(d) {
        return d.source.y;
      })
      .attr("x2", function(d) {
        return d.target.x;
      })
      .attr("y2", function(d) {
        return d.target.y;
      });
    
  //   node
  //     .attr("cx", function(d) {
  //       return d.x;
  //     })
  //     .attr("cy", function(d) {
  //       return d.y;
  //     });
  // 
}

  function dragstarted(d) {
    if (!d3.event.active) simulation.alphaTarget(0.3).restart();
    d.fx = d.x;
    d.fy = d.y;
  }

  function dragged(d) {
    d.fx = d3.event.x;
    d.fy = d3.event.y;
  }

  function dragended(d) {
    if (!d3.event.active) simulation.alphaTarget(0);
    d.fx = null;
    d.fy = null;
  }
 function gravity(alpha){
  return function(d){
    d.y+=(d.cy -d.y)*alpha;
    d.x +=(d.cx-d.x)*alpha;
  };
 }
 


