
  //initilize svg or grab svg
  var svg = d3.select("svg");
  var width = svg.attr("width");
  var height = svg.attr("height");
  var color = d3.scaleOrdinal(d3.schemeCategory20b);
 
 
  //intialize data
  var graph = {
    nodes: [
      { name:"KING HENRY VI", size:"82", color:"rgb(83,11,225)"},
{ name:"QUEEN MARGARET", size:"61", color:"rgb(62,88,95)"},
{ name:"ALL", size:"12", color:"rgb(104,212,88)"},
{ name:"SUFFOLK", size:"66", color:"rgb(16,126,131)"},
{ name:"GLOUCESTER", size:"69", color:"rgb(161,241,67)"},
{ name:"CARDINAL", size:"31", color:"rgb(48,126,71)"},
{ name:"SALISBURY", size:"17", color:"rgb(68,153,187)"},
{ name:"WARWICK", size:"32", color:"rgb(30,246,9)"},
{ name:"YORK", size:"58", color:"rgb(106,183,12)"},
{ name:"BUCKINGHAM", size:"24", color:"rgb(252,215,14)"},
{ name:"SOMERSET", size:"11", color:"rgb(153,152,144)"},
{ name:"DUCHESS", size:"21", color:"rgb(242,54,126)"},
{ name:"Messenger", size:"5", color:"rgb(16,79,227)"},
{ name:"HUME", size:"6", color:"rgb(172,142,9)"},
{ name:"First Petitioner", size:"3", color:"rgb(43,104,173)"},
{ name:"Second Petitioner", size:"3", color:"rgb(236,15,40)"},
{ name:"PETER", size:"9", color:"rgb(58,188,221)"},
{ name:"HORNER", size:"6", color:"rgb(82,24,64)"},
{ name:"BOLINGBROKE", size:"7", color:"rgb(213,78,245)"},
{ name:"Spirit", size:"5", color:"rgb(102,46,188)"},
{ name:"MARGARET JOURDAIN", size:"1", color:"rgb(245,174,173)"},
{ name:"Townsman", size:"2", color:"rgb(13,63,151)"},
{ name:"SIMPCOX", size:"18", color:"rgb(239,101,83)"},
{ name:"Wife", size:"7", color:"rgb(241,216,81)"},
{ name:"Mayor", size:"2", color:"rgb(109,74,210)"},
{ name:"Beadle", size:"1", color:"rgb(83,124,196)"},
{ name:"BOTH", size:"1", color:"rgb(41,133,113)"},
{ name:"First Neighbour", size:"1", color:"rgb(101,93,243)"},
{ name:"Second Neighbour", size:"1", color:"rgb(155,11,190)"},
{ name:"Third Neighbour", size:"1", color:"rgb(130,74,48)"},
{ name:"Servants", size:"1", color:"rgb(166,192,4)"},
{ name:"Servant", size:"1", color:"rgb(47,50,236)"},
{ name:"Herald", size:"1", color:"rgb(240,121,115)"},
{ name:"Sheriff", size:"2", color:"rgb(110,118,74)"},
{ name:"STANLEY", size:"4", color:"rgb(160,216,132)"},
{ name:"Post", size:"1", color:"rgb(233,103,84)"},
{ name:"First Murderer", size:"3", color:"rgb(146,2,120)"},
{ name:"Second Murderer", size:"1", color:"rgb(136,223,99)"},
{ name:"First Murder", size:"1", color:"rgb(25,139,76)"},
{ name:"Commons", size:"2", color:"rgb(227,66,175)"},
{ name:"VAUX", size:"1", color:"rgb(213,120,34)"},
{ name:"Captain", size:"11", color:"rgb(213,203,243)"},
{ name:"First Gentleman", size:"4", color:"rgb(179,18,33)"},
{ name:"Master", size:"1", color:"rgb(158,146,143)"},
{ name:"Second Gentleman", size:"1", color:"rgb(45,215,238)"},
{ name:"WHITMORE", size:"8", color:"rgb(209,102,1)"},
{ name:"BEVIS", size:"9", color:"rgb(94,0,223)"},
{ name:"HOLLAND", size:"10", color:"rgb(255,95,250)"},
{ name:"CADE", size:"58", color:"rgb(180,152,115)"},
{ name:"DICK", size:"24", color:"rgb(123,170,100)"},
{ name:"SMITH", size:"9", color:"rgb(162,223,90)"},
{ name:"Clerk", size:"2", color:"rgb(230,58,143)"},
{ name:"MICHAEL", size:"3", color:"rgb(162,180,215)"},
{ name:"SIR HUMPHREY", size:"6", color:"rgb(185,35,220)"},
{ name:"WILLIAM STAFFORD", size:"5", color:"rgb(248,188,243)"},
{ name:"SAY", size:"13", color:"rgb(243,124,215)"},
{ name:"SCALES", size:"2", color:"rgb(69,157,135)"},
{ name:"First Citizen", size:"1", color:"rgb(234,145,206)"},
{ name:"Soldier", size:"1", color:"rgb(210,34,169)"},
{ name:"CLIFFORD", size:"17", color:"rgb(48,228,88)"},
{ name:"IDEN", size:"9", color:"rgb(70,87,255)"},
{ name:"EDWARD", size:"1", color:"rgb(46,104,153)"},
{ name:"RICHARD", size:"6", color:"rgb(35,94,194)"},
{ name:"YOUNG CLIFFORD", size:"4", color:"rgb(116,200,191)"}],
    links: [{source:"KING HENRY VI", target:"QUEEN MARGARET"},
    {source:"QUEEN MARGARET", target:"KING HENRY VI"},
    {source:"KING HENRY VI", target:"ALL"},
    {source:"ALL", target:"QUEEN MARGARET"},
    {source:"QUEEN MARGARET", target:"SUFFOLK"},
    {source:"SUFFOLK", target:"GLOUCESTER"},
    {source:"GLOUCESTER", target:"KING HENRY VI"},
    {source:"KING HENRY VI", target:"GLOUCESTER"},
    {source:"GLOUCESTER", target:"KING HENRY VI"},
    {source:"KING HENRY VI", target:"CARDINAL"},
    {source:"CARDINAL", target:"KING HENRY VI"},
    {source:"KING HENRY VI", target:"GLOUCESTER"},
    {source:"GLOUCESTER", target:"CARDINAL"},
    {source:"CARDINAL", target:"GLOUCESTER"},
    {source:"GLOUCESTER", target:"SALISBURY"},
    {source:"SALISBURY", target:"WARWICK"},
    {source:"WARWICK", target:"YORK"},
    {source:"YORK", target:"GLOUCESTER"},
    {source:"GLOUCESTER", target:"CARDINAL"},
    {source:"CARDINAL", target:"GLOUCESTER"},
    {source:"GLOUCESTER", target:"CARDINAL"},
    {source:"CARDINAL", target:"BUCKINGHAM"},
    {source:"BUCKINGHAM", target:"CARDINAL"},
    {source:"CARDINAL", target:"SOMERSET"},
    {source:"SOMERSET", target:"BUCKINGHAM"},
    {source:"BUCKINGHAM", target:"SALISBURY"},
    {source:"SALISBURY", target:"WARWICK"},
    {source:"WARWICK", target:"YORK"},
    {source:"YORK", target:"SALISBURY"},
    {source:"SALISBURY", target:"WARWICK"},
    {source:"WARWICK", target:"YORK"},
    {source:"YORK", target:"DUCHESS"},
    {source:"DUCHESS", target:"GLOUCESTER"},
    {source:"GLOUCESTER", target:"DUCHESS"},
    {source:"DUCHESS", target:"GLOUCESTER"},
    {source:"GLOUCESTER", target:"DUCHESS"},
    {source:"DUCHESS", target:"GLOUCESTER"},
    {source:"GLOUCESTER", target:"DUCHESS"},
    {source:"DUCHESS", target:"GLOUCESTER"},
    {source:"GLOUCESTER", target:"Messenger"},
    {source:"Messenger", target:"GLOUCESTER"},
    {source:"GLOUCESTER", target:"DUCHESS"},
    {source:"DUCHESS", target:"HUME"},
    {source:"HUME", target:"DUCHESS"},
    {source:"DUCHESS", target:"HUME"},
    {source:"HUME", target:"DUCHESS"},
    {source:"DUCHESS", target:"HUME"},
    {source:"HUME", target:"DUCHESS"},
    {source:"DUCHESS", target:"HUME"},
    {source:"HUME", target:"First Petitioner"},
    {source:"First Petitioner", target:"Second Petitioner"},
    {source:"Second Petitioner", target:"PETER"},
    {source:"PETER", target:"Second Petitioner"},
    {source:"Second Petitioner", target:"SUFFOLK"},
    {source:"SUFFOLK", target:"First Petitioner"},
    {source:"First Petitioner", target:"QUEEN MARGARET"},
    {source:"QUEEN MARGARET", target:"First Petitioner"},
    {source:"First Petitioner", target:"SUFFOLK"},
    {source:"SUFFOLK", target:"Second Petitioner"},
    {source:"Second Petitioner", target:"PETER"},
    {source:"PETER", target:"QUEEN MARGARET"},
    {source:"QUEEN MARGARET", target:"PETER"},
    {source:"PETER", target:"SUFFOLK"},
    {source:"SUFFOLK", target:"QUEEN MARGARET"},
    {source:"QUEEN MARGARET", target:"ALL"},
    {source:"ALL", target:"QUEEN MARGARET"},
    {source:"QUEEN MARGARET", target:"SUFFOLK"},
    {source:"SUFFOLK", target:"QUEEN MARGARET"},
    {source:"QUEEN MARGARET", target:"SUFFOLK"},
    {source:"SUFFOLK", target:"QUEEN MARGARET"},
    {source:"QUEEN MARGARET", target:"SUFFOLK"},
    {source:"SUFFOLK", target:"KING HENRY VI"},
    {source:"KING HENRY VI", target:"YORK"},
    {source:"YORK", target:"SOMERSET"},
    {source:"SOMERSET", target:"WARWICK"},
    {source:"WARWICK", target:"CARDINAL"},
    {source:"CARDINAL", target:"WARWICK"},
    {source:"WARWICK", target:"BUCKINGHAM"},
    {source:"BUCKINGHAM", target:"WARWICK"},
    {source:"WARWICK", target:"SALISBURY"},
    {source:"SALISBURY", target:"QUEEN MARGARET"},
    {source:"QUEEN MARGARET", target:"GLOUCESTER"},
    {source:"GLOUCESTER", target:"QUEEN MARGARET"},
    {source:"QUEEN MARGARET", target:"GLOUCESTER"},
    {source:"GLOUCESTER", target:"SUFFOLK"},
    {source:"SUFFOLK", target:"CARDINAL"},
    {source:"CARDINAL", target:"SOMERSET"},
    {source:"SOMERSET", target:"BUCKINGHAM"},
    {source:"BUCKINGHAM", target:"QUEEN MARGARET"},
    {source:"QUEEN MARGARET", target:"DUCHESS"},
    {source:"DUCHESS", target:"KING HENRY VI"},
    {source:"KING HENRY VI", target:"DUCHESS"},
    {source:"DUCHESS", target:"BUCKINGHAM"},
    {source:"BUCKINGHAM", target:"GLOUCESTER"},
    {source:"GLOUCESTER", target:"SUFFOLK"},
    {source:"SUFFOLK", target:"YORK"},
    {source:"YORK", target:"WARWICK"},
    {source:"WARWICK", target:"SUFFOLK"},
    {source:"SUFFOLK", target:"WARWICK"},
    {source:"WARWICK", target:"SUFFOLK"},
    {source:"SUFFOLK", target:"YORK"},
    {source:"YORK", target:"KING HENRY VI"},
    {source:"KING HENRY VI", target:"SUFFOLK"},
    {source:"SUFFOLK", target:"KING HENRY VI"},
    {source:"KING HENRY VI", target:"HORNER"},
    {source:"HORNER", target:"PETER"},
    {source:"PETER", target:"YORK"},
    {source:"YORK", target:"HORNER"},
    {source:"HORNER", target:"KING HENRY VI"},
    {source:"KING HENRY VI", target:"GLOUCESTER"},
    {source:"GLOUCESTER", target:"SOMERSET"},
    {source:"SOMERSET", target:"HORNER"},
    {source:"HORNER", target:"PETER"},
    {source:"PETER", target:"GLOUCESTER"},
    {source:"GLOUCESTER", target:"KING HENRY VI"},
    {source:"KING HENRY VI", target:"HUME"},
    {source:"HUME", target:"BOLINGBROKE"},
    {source:"BOLINGBROKE", target:"HUME"},
    {source:"HUME", target:"BOLINGBROKE"},
    {source:"BOLINGBROKE", target:"DUCHESS"},
    {source:"DUCHESS", target:"BOLINGBROKE"},
    {source:"BOLINGBROKE", target:"Spirit"},
    {source:"Spirit", target:"MARGARET JOURDAIN"},
    {source:"MARGARET JOURDAIN", target:"Spirit"},
    {source:"Spirit", target:"BOLINGBROKE"},
    {source:"BOLINGBROKE", target:"Spirit"},
    {source:"Spirit", target:"BOLINGBROKE"},
    {source:"BOLINGBROKE", target:"Spirit"},
    {source:"Spirit", target:"BOLINGBROKE"},
    {source:"BOLINGBROKE", target:"Spirit"},
    {source:"Spirit", target:"BOLINGBROKE"},
    {source:"BOLINGBROKE", target:"YORK"},
    {source:"YORK", target:"DUCHESS"},
    {source:"DUCHESS", target:"BUCKINGHAM"},
    {source:"BUCKINGHAM", target:"YORK"},
    {source:"YORK", target:"BUCKINGHAM"},
    {source:"BUCKINGHAM", target:"YORK"},
    {source:"YORK", target:"QUEEN MARGARET"},
    {source:"QUEEN MARGARET", target:"KING HENRY VI"},
    {source:"KING HENRY VI", target:"SUFFOLK"},
    {source:"SUFFOLK", target:"GLOUCESTER"},
    {source:"GLOUCESTER", target:"CARDINAL"},
    {source:"CARDINAL", target:"GLOUCESTER"},
    {source:"GLOUCESTER", target:"KING HENRY VI"},
    {source:"KING HENRY VI", target:"CARDINAL"},
    {source:"CARDINAL", target:"GLOUCESTER"},
    {source:"GLOUCESTER", target:"SUFFOLK"},
    {source:"SUFFOLK", target:"GLOUCESTER"},
    {source:"GLOUCESTER", target:"SUFFOLK"},
    {source:"SUFFOLK", target:"GLOUCESTER"},
    {source:"GLOUCESTER", target:"QUEEN MARGARET"},
    {source:"QUEEN MARGARET", target:"KING HENRY VI"},
    {source:"KING HENRY VI", target:"CARDINAL"},
    {source:"CARDINAL", target:"GLOUCESTER"},
    {source:"GLOUCESTER", target:"CARDINAL"},
    {source:"CARDINAL", target:"GLOUCESTER"},
    {source:"GLOUCESTER", target:"CARDINAL"},
    {source:"CARDINAL", target:"KING HENRY VI"},
    {source:"KING HENRY VI", target:"CARDINAL"},
    {source:"CARDINAL", target:"GLOUCESTER"},
    {source:"GLOUCESTER", target:"CARDINAL"},
    {source:"CARDINAL", target:"GLOUCESTER"},
    {source:"GLOUCESTER", target:"KING HENRY VI"},
    {source:"KING HENRY VI", target:"GLOUCESTER"},
    {source:"GLOUCESTER", target:"CARDINAL"},
    {source:"CARDINAL", target:"KING HENRY VI"},
    {source:"KING HENRY VI", target:"GLOUCESTER"},
    {source:"GLOUCESTER", target:"Townsman"},
    {source:"Townsman", target:"SUFFOLK"},
    {source:"SUFFOLK", target:"Townsman"},
    {source:"Townsman", target:"KING HENRY VI"},
    {source:"KING HENRY VI", target:"CARDINAL"},
    {source:"CARDINAL", target:"KING HENRY VI"},
    {source:"KING HENRY VI", target:"GLOUCESTER"},
    {source:"GLOUCESTER", target:"KING HENRY VI"},
    {source:"KING HENRY VI", target:"SIMPCOX"},
    {source:"SIMPCOX", target:"Wife"},
    {source:"Wife", target:"SUFFOLK"},
    {source:"SUFFOLK", target:"Wife"},
    {source:"Wife", target:"GLOUCESTER"},
    {source:"GLOUCESTER", target:"KING HENRY VI"},
    {source:"KING HENRY VI", target:"SIMPCOX"},
    {source:"SIMPCOX", target:"KING HENRY VI"},
    {source:"KING HENRY VI", target:"QUEEN MARGARET"},
    {source:"QUEEN MARGARET", target:"SIMPCOX"},
    {source:"SIMPCOX", target:"Wife"},
    {source:"Wife", target:"CARDINAL"},
    {source:"CARDINAL", target:"SIMPCOX"},
    {source:"SIMPCOX", target:"SUFFOLK"},
    {source:"SUFFOLK", target:"SIMPCOX"},
    {source:"SIMPCOX", target:"Wife"},
    {source:"Wife", target:"GLOUCESTER"},
    {source:"GLOUCESTER", target:"SIMPCOX"},
    {source:"SIMPCOX", target:"GLOUCESTER"},
    {source:"GLOUCESTER", target:"SIMPCOX"},
    {source:"SIMPCOX", target:"Wife"},
    {source:"Wife", target:"GLOUCESTER"},
    {source:"GLOUCESTER", target:"SIMPCOX"},
    {source:"SIMPCOX", target:"GLOUCESTER"},
    {source:"GLOUCESTER", target:"SIMPCOX"},
    {source:"SIMPCOX", target:"GLOUCESTER"},
    {source:"GLOUCESTER", target:"SIMPCOX"},
    {source:"SIMPCOX", target:"GLOUCESTER"},
    {source:"GLOUCESTER", target:"SIMPCOX"},
    {source:"SIMPCOX", target:"KING HENRY VI"},
    {source:"KING HENRY VI", target:"SUFFOLK"},
    {source:"SUFFOLK", target:"GLOUCESTER"},
    {source:"GLOUCESTER", target:"Wife"},
    {source:"Wife", target:"GLOUCESTER"},
    {source:"GLOUCESTER", target:"SIMPCOX"},
    {source:"SIMPCOX", target:"GLOUCESTER"},
    {source:"GLOUCESTER", target:"SIMPCOX"},
    {source:"SIMPCOX", target:"GLOUCESTER"},
    {source:"GLOUCESTER", target:"SIMPCOX"},
    {source:"SIMPCOX", target:"GLOUCESTER"},
    {source:"GLOUCESTER", target:"SIMPCOX"},
    {source:"SIMPCOX", target:"GLOUCESTER"},
    {source:"GLOUCESTER", target:"SIMPCOX"},
    {source:"SIMPCOX", target:"GLOUCESTER"},
    {source:"GLOUCESTER", target:"Mayor"},
    {source:"Mayor", target:"GLOUCESTER"},
    {source:"GLOUCESTER", target:"Mayor"},
    {source:"Mayor", target:"GLOUCESTER"},
    {source:"GLOUCESTER", target:"SIMPCOX"},
    {source:"SIMPCOX", target:"GLOUCESTER"},
    {source:"GLOUCESTER", target:"Beadle"},
    {source:"Beadle", target:"SIMPCOX"},
    {source:"SIMPCOX", target:"KING HENRY VI"},
    {source:"KING HENRY VI", target:"QUEEN MARGARET"},
    {source:"QUEEN MARGARET", target:"GLOUCESTER"},
    {source:"GLOUCESTER", target:"Wife"},
    {source:"Wife", target:"GLOUCESTER"},
    {source:"GLOUCESTER", target:"CARDINAL"},
    {source:"CARDINAL", target:"SUFFOLK"},
    {source:"SUFFOLK", target:"GLOUCESTER"},
    {source:"GLOUCESTER", target:"KING HENRY VI"},
    {source:"KING HENRY VI", target:"BUCKINGHAM"},
    {source:"BUCKINGHAM", target:"CARDINAL"},
    {source:"CARDINAL", target:"GLOUCESTER"},
    {source:"GLOUCESTER", target:"KING HENRY VI"},
    {source:"KING HENRY VI", target:"QUEEN MARGARET"},
    {source:"QUEEN MARGARET", target:"GLOUCESTER"},
    {source:"GLOUCESTER", target:"KING HENRY VI"},
    {source:"KING HENRY VI", target:"YORK"},
    {source:"YORK", target:"SALISBURY"},
    {source:"SALISBURY", target:"WARWICK"},
    {source:"WARWICK", target:"YORK"},
    {source:"YORK", target:"WARWICK"},
    {source:"WARWICK", target:"YORK"},
    {source:"YORK", target:"SALISBURY"},
    {source:"SALISBURY", target:"YORK"},
    {source:"YORK", target:"SALISBURY"},
    {source:"SALISBURY", target:"YORK"},
    {source:"YORK", target:"WARWICK"},
    {source:"WARWICK", target:"BOTH"},
    {source:"BOTH", target:"YORK"},
    {source:"YORK", target:"SALISBURY"},
    {source:"SALISBURY", target:"WARWICK"},
    {source:"WARWICK", target:"YORK"},
    {source:"YORK", target:"KING HENRY VI"},
    {source:"KING HENRY VI", target:"DUCHESS"},
    {source:"DUCHESS", target:"GLOUCESTER"},
    {source:"GLOUCESTER", target:"KING HENRY VI"},
    {source:"KING HENRY VI", target:"QUEEN MARGARET"},
    {source:"QUEEN MARGARET", target:"GLOUCESTER"},
    {source:"GLOUCESTER", target:"QUEEN MARGARET"},
    {source:"QUEEN MARGARET", target:"SUFFOLK"},
    {source:"SUFFOLK", target:"YORK"},
    {source:"YORK", target:"QUEEN MARGARET"},
    {source:"QUEEN MARGARET", target:"KING HENRY VI"},
    {source:"KING HENRY VI", target:"YORK"},
    {source:"YORK", target:"First Neighbour"},
    {source:"First Neighbour", target:"Second Neighbour"},
    {source:"Second Neighbour", target:"Third Neighbour"},
    {source:"Third Neighbour", target:"HORNER"},
    {source:"HORNER", target:"PETER"},
    {source:"PETER", target:"SALISBURY"},
    {source:"SALISBURY", target:"PETER"},
    {source:"PETER", target:"SALISBURY"},
    {source:"SALISBURY", target:"PETER"},
    {source:"PETER", target:"SALISBURY"},
    {source:"SALISBURY", target:"HORNER"},
    {source:"HORNER", target:"YORK"},
    {source:"YORK", target:"HORNER"},
    {source:"HORNER", target:"YORK"},
    {source:"YORK", target:"PETER"},
    {source:"PETER", target:"KING HENRY VI"},
    {source:"KING HENRY VI", target:"GLOUCESTER"},
    {source:"GLOUCESTER", target:"Servants"},
    {source:"Servants", target:"GLOUCESTER"},
    {source:"GLOUCESTER", target:"Servant"},
    {source:"Servant", target:"GLOUCESTER"},
    {source:"GLOUCESTER", target:"DUCHESS"},
    {source:"DUCHESS", target:"GLOUCESTER"},
    {source:"GLOUCESTER", target:"DUCHESS"},
    {source:"DUCHESS", target:"GLOUCESTER"},
    {source:"GLOUCESTER", target:"Herald"},
    {source:"Herald", target:"GLOUCESTER"},
    {source:"GLOUCESTER", target:"Sheriff"},
    {source:"Sheriff", target:"GLOUCESTER"},
    {source:"GLOUCESTER", target:"STANLEY"},
    {source:"STANLEY", target:"GLOUCESTER"},
    {source:"GLOUCESTER", target:"DUCHESS"},
    {source:"DUCHESS", target:"GLOUCESTER"},
    {source:"GLOUCESTER", target:"DUCHESS"},
    {source:"DUCHESS", target:"STANLEY"},
    {source:"STANLEY", target:"DUCHESS"},
    {source:"DUCHESS", target:"STANLEY"},
    {source:"STANLEY", target:"DUCHESS"},
    {source:"DUCHESS", target:"Sheriff"},
    {source:"Sheriff", target:"DUCHESS"},
    {source:"DUCHESS", target:"STANLEY"},
    {source:"STANLEY", target:"DUCHESS"},
    {source:"DUCHESS", target:"KING HENRY VI"},
    {source:"KING HENRY VI", target:"QUEEN MARGARET"},
    {source:"QUEEN MARGARET", target:"SUFFOLK"},
    {source:"SUFFOLK", target:"CARDINAL"},
    {source:"CARDINAL", target:"YORK"},
    {source:"YORK", target:"BUCKINGHAM"},
    {source:"BUCKINGHAM", target:"KING HENRY VI"},
    {source:"KING HENRY VI", target:"QUEEN MARGARET"},
    {source:"QUEEN MARGARET", target:"SOMERSET"},
    {source:"SOMERSET", target:"KING HENRY VI"},
    {source:"KING HENRY VI", target:"SOMERSET"},
    {source:"SOMERSET", target:"KING HENRY VI"},
    {source:"KING HENRY VI", target:"YORK"},
    {source:"YORK", target:"GLOUCESTER"},
    {source:"GLOUCESTER", target:"SUFFOLK"},
    {source:"SUFFOLK", target:"GLOUCESTER"},
    {source:"GLOUCESTER", target:"YORK"},
    {source:"YORK", target:"GLOUCESTER"},
    {source:"GLOUCESTER", target:"CARDINAL"},
    {source:"CARDINAL", target:"GLOUCESTER"},
    {source:"GLOUCESTER", target:"YORK"},
    {source:"YORK", target:"GLOUCESTER"},
    {source:"GLOUCESTER", target:"SUFFOLK"},
    {source:"SUFFOLK", target:"KING HENRY VI"},
    {source:"KING HENRY VI", target:"GLOUCESTER"},
    {source:"GLOUCESTER", target:"CARDINAL"},
    {source:"CARDINAL", target:"SUFFOLK"},
    {source:"SUFFOLK", target:"QUEEN MARGARET"},
    {source:"QUEEN MARGARET", target:"GLOUCESTER"},
    {source:"GLOUCESTER", target:"BUCKINGHAM"},
    {source:"BUCKINGHAM", target:"CARDINAL"},
    {source:"CARDINAL", target:"GLOUCESTER"},
    {source:"GLOUCESTER", target:"KING HENRY VI"},
    {source:"KING HENRY VI", target:"QUEEN MARGARET"},
    {source:"QUEEN MARGARET", target:"KING HENRY VI"},
    {source:"KING HENRY VI", target:"QUEEN MARGARET"},
    {source:"QUEEN MARGARET", target:"CARDINAL"},
    {source:"CARDINAL", target:"SUFFOLK"},
    {source:"SUFFOLK", target:"YORK"},
    {source:"YORK", target:"SUFFOLK"},
    {source:"SUFFOLK", target:"YORK"},
    {source:"YORK", target:"QUEEN MARGARET"},
    {source:"QUEEN MARGARET", target:"SUFFOLK"},
    {source:"SUFFOLK", target:"QUEEN MARGARET"},
    {source:"QUEEN MARGARET", target:"SUFFOLK"},
    {source:"SUFFOLK", target:"CARDINAL"},
    {source:"CARDINAL", target:"SUFFOLK"},
    {source:"SUFFOLK", target:"QUEEN MARGARET"},
    {source:"QUEEN MARGARET", target:"YORK"},
    {source:"YORK", target:"Post"},
    {source:"Post", target:"CARDINAL"},
    {source:"CARDINAL", target:"YORK"},
    {source:"YORK", target:"SOMERSET"},
    {source:"SOMERSET", target:"YORK"},
    {source:"YORK", target:"QUEEN MARGARET"},
    {source:"QUEEN MARGARET", target:"YORK"},
    {source:"YORK", target:"SOMERSET"},
    {source:"SOMERSET", target:"CARDINAL"},
    {source:"CARDINAL", target:"YORK"},
    {source:"YORK", target:"SUFFOLK"},
    {source:"SUFFOLK", target:"YORK"},
    {source:"YORK", target:"SUFFOLK"},
    {source:"SUFFOLK", target:"CARDINAL"},
    {source:"CARDINAL", target:"YORK"},
    {source:"YORK", target:"SUFFOLK"},
    {source:"SUFFOLK", target:"YORK"},
    {source:"YORK", target:"First Murderer"},
    {source:"First Murderer", target:"Second Murderer"},
    {source:"Second Murderer", target:"First Murder"},
    {source:"First Murder", target:"SUFFOLK"},
    {source:"SUFFOLK", target:"First Murderer"},
    {source:"First Murderer", target:"SUFFOLK"},
    {source:"SUFFOLK", target:"First Murderer"},
    {source:"First Murderer", target:"SUFFOLK"},
    {source:"SUFFOLK", target:"KING HENRY VI"},
    {source:"KING HENRY VI", target:"SUFFOLK"},
    {source:"SUFFOLK", target:"KING HENRY VI"},
    {source:"KING HENRY VI", target:"QUEEN MARGARET"},
    {source:"QUEEN MARGARET", target:"KING HENRY VI"},
    {source:"KING HENRY VI", target:"SUFFOLK"},
    {source:"SUFFOLK", target:"QUEEN MARGARET"},
    {source:"QUEEN MARGARET", target:"CARDINAL"},
    {source:"CARDINAL", target:"QUEEN MARGARET"},
    {source:"QUEEN MARGARET", target:"SOMERSET"},
    {source:"SOMERSET", target:"QUEEN MARGARET"},
    {source:"QUEEN MARGARET", target:"SUFFOLK"},
    {source:"SUFFOLK", target:"KING HENRY VI"},
    {source:"KING HENRY VI", target:"QUEEN MARGARET"},
    {source:"QUEEN MARGARET", target:"SUFFOLK"},
    {source:"SUFFOLK", target:"KING HENRY VI"},
    {source:"KING HENRY VI", target:"QUEEN MARGARET"},
    {source:"QUEEN MARGARET", target:"KING HENRY VI"},
    {source:"KING HENRY VI", target:"QUEEN MARGARET"},
    {source:"QUEEN MARGARET", target:"WARWICK"},
    {source:"WARWICK", target:"KING HENRY VI"},
    {source:"KING HENRY VI", target:"WARWICK"},
    {source:"WARWICK", target:"KING HENRY VI"},
    {source:"KING HENRY VI", target:"WARWICK"},
    {source:"WARWICK", target:"KING HENRY VI"},
    {source:"KING HENRY VI", target:"WARWICK"},
    {source:"WARWICK", target:"SUFFOLK"},
    {source:"SUFFOLK", target:"WARWICK"},
    {source:"WARWICK", target:"SUFFOLK"},
    {source:"SUFFOLK", target:"WARWICK"},
    {source:"WARWICK", target:"QUEEN MARGARET"},
    {source:"QUEEN MARGARET", target:"WARWICK"},
    {source:"WARWICK", target:"QUEEN MARGARET"},
    {source:"QUEEN MARGARET", target:"SUFFOLK"},
    {source:"SUFFOLK", target:"WARWICK"},
    {source:"WARWICK", target:"QUEEN MARGARET"},
    {source:"QUEEN MARGARET", target:"WARWICK"},
    {source:"WARWICK", target:"SUFFOLK"},
    {source:"SUFFOLK", target:"WARWICK"},
    {source:"WARWICK", target:"SUFFOLK"},
    {source:"SUFFOLK", target:"WARWICK"},
    {source:"WARWICK", target:"KING HENRY VI"},
    {source:"KING HENRY VI", target:"QUEEN MARGARET"},
    {source:"QUEEN MARGARET", target:"KING HENRY VI"},
    {source:"KING HENRY VI", target:"SUFFOLK"},
    {source:"SUFFOLK", target:"SALISBURY"},
    {source:"SALISBURY", target:"Commons"},
    {source:"Commons", target:"SUFFOLK"},
    {source:"SUFFOLK", target:"Commons"},
    {source:"Commons", target:"KING HENRY VI"},
    {source:"KING HENRY VI", target:"QUEEN MARGARET"},
    {source:"QUEEN MARGARET", target:"KING HENRY VI"},
    {source:"KING HENRY VI", target:"QUEEN MARGARET"},
    {source:"QUEEN MARGARET", target:"SUFFOLK"},
    {source:"SUFFOLK", target:"QUEEN MARGARET"},
    {source:"QUEEN MARGARET", target:"SUFFOLK"},
    {source:"SUFFOLK", target:"QUEEN MARGARET"},
    {source:"QUEEN MARGARET", target:"SUFFOLK"},
    {source:"SUFFOLK", target:"QUEEN MARGARET"},
    {source:"QUEEN MARGARET", target:"SUFFOLK"},
    {source:"SUFFOLK", target:"QUEEN MARGARET"},
    {source:"QUEEN MARGARET", target:"VAUX"},
    {source:"VAUX", target:"QUEEN MARGARET"},
    {source:"QUEEN MARGARET", target:"SUFFOLK"},
    {source:"SUFFOLK", target:"QUEEN MARGARET"},
    {source:"QUEEN MARGARET", target:"SUFFOLK"},
    {source:"SUFFOLK", target:"QUEEN MARGARET"},
    {source:"QUEEN MARGARET", target:"SUFFOLK"},
    {source:"SUFFOLK", target:"QUEEN MARGARET"},
    {source:"QUEEN MARGARET", target:"KING HENRY VI"},
    {source:"KING HENRY VI", target:"CARDINAL"},
    {source:"CARDINAL", target:"KING HENRY VI"},
    {source:"KING HENRY VI", target:"WARWICK"},
    {source:"WARWICK", target:"CARDINAL"},
    {source:"CARDINAL", target:"KING HENRY VI"},
    {source:"KING HENRY VI", target:"WARWICK"},
    {source:"WARWICK", target:"SALISBURY"},
    {source:"SALISBURY", target:"KING HENRY VI"},
    {source:"KING HENRY VI", target:"WARWICK"},
    {source:"WARWICK", target:"KING HENRY VI"},
    {source:"KING HENRY VI", target:"Captain"},
    {source:"Captain", target:"First Gentleman"},
    {source:"First Gentleman", target:"Master"},
    {source:"Master", target:"Captain"},
    {source:"Captain", target:"First Gentleman"},
    {source:"First Gentleman", target:"Second Gentleman"},
    {source:"Second Gentleman", target:"WHITMORE"},
    {source:"WHITMORE", target:"Captain"},
    {source:"Captain", target:"SUFFOLK"},
    {source:"SUFFOLK", target:"WHITMORE"},
    {source:"WHITMORE", target:"SUFFOLK"},
    {source:"SUFFOLK", target:"WHITMORE"},
    {source:"WHITMORE", target:"SUFFOLK"},
    {source:"SUFFOLK", target:"WHITMORE"},
    {source:"WHITMORE", target:"SUFFOLK"},
    {source:"SUFFOLK", target:"Captain"},
    {source:"Captain", target:"SUFFOLK"},
    {source:"SUFFOLK", target:"WHITMORE"},
    {source:"WHITMORE", target:"Captain"},
    {source:"Captain", target:"SUFFOLK"},
    {source:"SUFFOLK", target:"Captain"},
    {source:"Captain", target:"SUFFOLK"},
    {source:"SUFFOLK", target:"Captain"},
    {source:"Captain", target:"SUFFOLK"},
    {source:"SUFFOLK", target:"Captain"},
    {source:"Captain", target:"SUFFOLK"},
    {source:"SUFFOLK", target:"Captain"},
    {source:"Captain", target:"WHITMORE"},
    {source:"WHITMORE", target:"SUFFOLK"},
    {source:"SUFFOLK", target:"WHITMORE"},
    {source:"WHITMORE", target:"First Gentleman"},
    {source:"First Gentleman", target:"SUFFOLK"},
    {source:"SUFFOLK", target:"Captain"},
    {source:"Captain", target:"SUFFOLK"},
    {source:"SUFFOLK", target:"Captain"},
    {source:"Captain", target:"WHITMORE"},
    {source:"WHITMORE", target:"First Gentleman"},
    {source:"First Gentleman", target:"BEVIS"},
    {source:"BEVIS", target:"HOLLAND"},
    {source:"HOLLAND", target:"BEVIS"},
    {source:"BEVIS", target:"HOLLAND"},
    {source:"HOLLAND", target:"BEVIS"},
    {source:"BEVIS", target:"HOLLAND"},
    {source:"HOLLAND", target:"BEVIS"},
    {source:"BEVIS", target:"HOLLAND"},
    {source:"HOLLAND", target:"BEVIS"},
    {source:"BEVIS", target:"HOLLAND"},
    {source:"HOLLAND", target:"BEVIS"},
    {source:"BEVIS", target:"HOLLAND"},
    {source:"HOLLAND", target:"BEVIS"},
    {source:"BEVIS", target:"HOLLAND"},
    {source:"HOLLAND", target:"BEVIS"},
    {source:"BEVIS", target:"HOLLAND"},
    {source:"HOLLAND", target:"CADE"},
    {source:"CADE", target:"DICK"},
    {source:"DICK", target:"CADE"},
    {source:"CADE", target:"DICK"},
    {source:"DICK", target:"CADE"},
    {source:"CADE", target:"DICK"},
    {source:"DICK", target:"CADE"},
    {source:"CADE", target:"DICK"},
    {source:"DICK", target:"CADE"},
    {source:"CADE", target:"DICK"},
    {source:"DICK", target:"SMITH"},
    {source:"SMITH", target:"CADE"},
    {source:"CADE", target:"DICK"},
    {source:"DICK", target:"CADE"},
    {source:"CADE", target:"SMITH"},
    {source:"SMITH", target:"CADE"},
    {source:"CADE", target:"DICK"},
    {source:"DICK", target:"CADE"},
    {source:"CADE", target:"SMITH"},
    {source:"SMITH", target:"DICK"},
    {source:"DICK", target:"CADE"},
    {source:"CADE", target:"ALL"},
    {source:"ALL", target:"CADE"},
    {source:"CADE", target:"DICK"},
    {source:"DICK", target:"CADE"},
    {source:"CADE", target:"SMITH"},
    {source:"SMITH", target:"CADE"},
    {source:"CADE", target:"SMITH"},
    {source:"SMITH", target:"CADE"},
    {source:"CADE", target:"SMITH"},
    {source:"SMITH", target:"CADE"},
    {source:"CADE", target:"DICK"},
    {source:"DICK", target:"CADE"},
    {source:"CADE", target:"Clerk"},
    {source:"Clerk", target:"DICK"},
    {source:"DICK", target:"CADE"},
    {source:"CADE", target:"CLERK"},
    {source:"CLERK", target:"ALL"},
    {source:"ALL", target:"CADE"},
    {source:"CADE", target:"MICHAEL"},
    {source:"MICHAEL", target:"CADE"},
    {source:"CADE", target:"MICHAEL"},
    {source:"MICHAEL", target:"CADE"},
    {source:"CADE", target:"MICHAEL"},
    {source:"MICHAEL", target:"CADE"},
    {source:"CADE", target:"SIR HUMPHREY"},
    {source:"SIR HUMPHREY", target:"WILLIAM STAFFORD"},
    {source:"WILLIAM STAFFORD", target:"CADE"},
    {source:"CADE", target:"SIR HUMPHREY"},
    {source:"SIR HUMPHREY", target:"CADE"},
    {source:"CADE", target:"WILLIAM STAFFORD"},
    {source:"WILLIAM STAFFORD", target:"CADE"},
    {source:"CADE", target:"SIR HUMPHREY"},
    {source:"SIR HUMPHREY", target:"CADE"},
    {source:"CADE", target:"WILLIAM STAFFORD"},
    {source:"WILLIAM STAFFORD", target:"CADE"},
    {source:"CADE", target:"DICK"},
    {source:"DICK", target:"SMITH"},
    {source:"SMITH", target:"SIR HUMPHREY"},
    {source:"SIR HUMPHREY", target:"ALL"},
    {source:"ALL", target:"WILLIAM STAFFORD"},
    {source:"WILLIAM STAFFORD", target:"CADE"},
    {source:"CADE", target:"DICK"},
    {source:"DICK", target:"CADE"},
    {source:"CADE", target:"SIR HUMPHREY"},
    {source:"SIR HUMPHREY", target:"CADE"},
    {source:"CADE", target:"ALL"},
    {source:"ALL", target:"WILLIAM STAFFORD"},
    {source:"WILLIAM STAFFORD", target:"SIR HUMPHREY"},
    {source:"SIR HUMPHREY", target:"CADE"},
    {source:"CADE", target:"DICK"},
    {source:"DICK", target:"CADE"},
    {source:"CADE", target:"DICK"},
    {source:"DICK", target:"CADE"},
    {source:"CADE", target:"DICK"},
    {source:"DICK", target:"CADE"},
    {source:"CADE", target:"DICK"},
    {source:"DICK", target:"CADE"},
    {source:"CADE", target:"QUEEN MARGARET"},
    {source:"QUEEN MARGARET", target:"BUCKINGHAM"},
    {source:"BUCKINGHAM", target:"KING HENRY VI"},
    {source:"KING HENRY VI", target:"QUEEN MARGARET"},
    {source:"QUEEN MARGARET", target:"KING HENRY VI"},
    {source:"KING HENRY VI", target:"SAY"},
    {source:"SAY", target:"KING HENRY VI"},
    {source:"KING HENRY VI", target:"QUEEN MARGARET"},
    {source:"QUEEN MARGARET", target:"KING HENRY VI"},
    {source:"KING HENRY VI", target:"Messenger"},
    {source:"Messenger", target:"KING HENRY VI"},
    {source:"KING HENRY VI", target:"BUCKINGHAM"},
    {source:"BUCKINGHAM", target:"QUEEN MARGARET"},
    {source:"QUEEN MARGARET", target:"KING HENRY VI"},
    {source:"KING HENRY VI", target:"SAY"},
    {source:"SAY", target:"Messenger"},
    {source:"Messenger", target:"BUCKINGHAM"},
    {source:"BUCKINGHAM", target:"KING HENRY VI"},
    {source:"KING HENRY VI", target:"QUEEN MARGARET"},
    {source:"QUEEN MARGARET", target:"KING HENRY VI"},
    {source:"KING HENRY VI", target:"BUCKINGHAM"},
    {source:"BUCKINGHAM", target:"SAY"},
    {source:"SAY", target:"SCALES"},
    {source:"SCALES", target:"First Citizen"},
    {source:"First Citizen", target:"SCALES"},
    {source:"SCALES", target:"CADE"},
    {source:"CADE", target:"Soldier"},
    {source:"Soldier", target:"CADE"},
    {source:"CADE", target:"SMITH"},
    {source:"SMITH", target:"DICK"},
    {source:"DICK", target:"CADE"},
    {source:"CADE", target:"DICK"},
    {source:"DICK", target:"CADE"},
    {source:"CADE", target:"DICK"},
    {source:"DICK", target:"HOLLAND"},
    {source:"HOLLAND", target:"SMITH"},
    {source:"SMITH", target:"CADE"},
    {source:"CADE", target:"HOLLAND"},
    {source:"HOLLAND", target:"CADE"},
    {source:"CADE", target:"Messenger"},
    {source:"Messenger", target:"CADE"},
    {source:"CADE", target:"SAY"},
    {source:"SAY", target:"CADE"},
    {source:"CADE", target:"DICK"},
    {source:"DICK", target:"SAY"},
    {source:"SAY", target:"DICK"},
    {source:"DICK", target:"SAY"},
    {source:"SAY", target:"CADE"},
    {source:"CADE", target:"SAY"},
    {source:"SAY", target:"CADE"},
    {source:"CADE", target:"SAY"},
    {source:"SAY", target:"BEVIS"},
    {source:"BEVIS", target:"SAY"},
    {source:"SAY", target:"CADE"},
    {source:"CADE", target:"SAY"},
    {source:"SAY", target:"CADE"},
    {source:"CADE", target:"DICK"},
    {source:"DICK", target:"SAY"},
    {source:"SAY", target:"CADE"},
    {source:"CADE", target:"SAY"},
    {source:"SAY", target:"CADE"},
    {source:"CADE", target:"ALL"},
    {source:"ALL", target:"SAY"},
    {source:"SAY", target:"CADE"},
    {source:"CADE", target:"DICK"},
    {source:"DICK", target:"CADE"},
    {source:"CADE", target:"ALL"},
    {source:"ALL", target:"CADE"},
    {source:"CADE", target:"BUCKINGHAM"},
    {source:"BUCKINGHAM", target:"CLIFFORD"},
    {source:"CLIFFORD", target:"ALL"},
    {source:"ALL", target:"CADE"},
    {source:"CADE", target:"ALL"},
    {source:"ALL", target:"CLIFFORD"},
    {source:"CLIFFORD", target:"ALL"},
    {source:"ALL", target:"CADE"},
    {source:"CADE", target:"BUCKINGHAM"},
    {source:"BUCKINGHAM", target:"KING HENRY VI"},
    {source:"KING HENRY VI", target:"BUCKINGHAM"},
    {source:"BUCKINGHAM", target:"KING HENRY VI"},
    {source:"KING HENRY VI", target:"CLIFFORD"},
    {source:"CLIFFORD", target:"KING HENRY VI"},
    {source:"KING HENRY VI", target:"ALL"},
    {source:"ALL", target:"Messenger"},
    {source:"Messenger", target:"KING HENRY VI"},
    {source:"KING HENRY VI", target:"SOMERSET"},
    {source:"SOMERSET", target:"KING HENRY VI"},
    {source:"KING HENRY VI", target:"BUCKINGHAM"},
    {source:"BUCKINGHAM", target:"KING HENRY VI"},
    {source:"KING HENRY VI", target:"CADE"},
    {source:"CADE", target:"IDEN"},
    {source:"IDEN", target:"CADE"},
    {source:"CADE", target:"IDEN"},
    {source:"IDEN", target:"CADE"},
    {source:"CADE", target:"IDEN"},
    {source:"IDEN", target:"CADE"},
    {source:"CADE", target:"IDEN"},
    {source:"IDEN", target:"CADE"},
    {source:"CADE", target:"IDEN"},
    {source:"IDEN", target:"YORK"},
    {source:"YORK", target:"BUCKINGHAM"},
    {source:"BUCKINGHAM", target:"YORK"},
    {source:"YORK", target:"BUCKINGHAM"},
    {source:"BUCKINGHAM", target:"YORK"},
    {source:"YORK", target:"BUCKINGHAM"},
    {source:"BUCKINGHAM", target:"YORK"},
    {source:"YORK", target:"BUCKINGHAM"},
    {source:"BUCKINGHAM", target:"YORK"},
    {source:"YORK", target:"BUCKINGHAM"},
    {source:"BUCKINGHAM", target:"KING HENRY VI"},
    {source:"KING HENRY VI", target:"YORK"},
    {source:"YORK", target:"KING HENRY VI"},
    {source:"KING HENRY VI", target:"YORK"},
    {source:"YORK", target:"IDEN"},
    {source:"IDEN", target:"KING HENRY VI"},
    {source:"KING HENRY VI", target:"IDEN"},
    {source:"IDEN", target:"KING HENRY VI"},
    {source:"KING HENRY VI", target:"IDEN"},
    {source:"IDEN", target:"BUCKINGHAM"},
    {source:"BUCKINGHAM", target:"KING HENRY VI"},
    {source:"KING HENRY VI", target:"IDEN"},
    {source:"IDEN", target:"KING HENRY VI"},
    {source:"KING HENRY VI", target:"QUEEN MARGARET"},
    {source:"QUEEN MARGARET", target:"YORK"},
    {source:"YORK", target:"SOMERSET"},
    {source:"SOMERSET", target:"YORK"},
    {source:"YORK", target:"QUEEN MARGARET"},
    {source:"QUEEN MARGARET", target:"YORK"},
    {source:"YORK", target:"QUEEN MARGARET"},
    {source:"QUEEN MARGARET", target:"CLIFFORD"},
    {source:"CLIFFORD", target:"YORK"},
    {source:"YORK", target:"CLIFFORD"},
    {source:"CLIFFORD", target:"KING HENRY VI"},
    {source:"KING HENRY VI", target:"CLIFFORD"},
    {source:"CLIFFORD", target:"QUEEN MARGARET"},
    {source:"QUEEN MARGARET", target:"YORK"},
    {source:"YORK", target:"EDWARD"},
    {source:"EDWARD", target:"RICHARD"},
    {source:"RICHARD", target:"CLIFFORD"},
    {source:"CLIFFORD", target:"YORK"},
    {source:"YORK", target:"CLIFFORD"},
    {source:"CLIFFORD", target:"RICHARD"},
    {source:"RICHARD", target:"CLIFFORD"},
    {source:"CLIFFORD", target:"YORK"},
    {source:"YORK", target:"CLIFFORD"},
    {source:"CLIFFORD", target:"KING HENRY VI"},
    {source:"KING HENRY VI", target:"SALISBURY"},
    {source:"SALISBURY", target:"KING HENRY VI"},
    {source:"KING HENRY VI", target:"SALISBURY"},
    {source:"SALISBURY", target:"KING HENRY VI"},
    {source:"KING HENRY VI", target:"SALISBURY"},
    {source:"SALISBURY", target:"QUEEN MARGARET"},
    {source:"QUEEN MARGARET", target:"KING HENRY VI"},
    {source:"KING HENRY VI", target:"YORK"},
    {source:"YORK", target:"CLIFFORD"},
    {source:"CLIFFORD", target:"WARWICK"},
    {source:"WARWICK", target:"CLIFFORD"},
    {source:"CLIFFORD", target:"WARWICK"},
    {source:"WARWICK", target:"CLIFFORD"},
    {source:"CLIFFORD", target:"YOUNG CLIFFORD"},
    {source:"YOUNG CLIFFORD", target:"RICHARD"},
    {source:"RICHARD", target:"YOUNG CLIFFORD"},
    {source:"YOUNG CLIFFORD", target:"RICHARD"},
    {source:"RICHARD", target:"WARWICK"},
    {source:"WARWICK", target:"YORK"},
    {source:"YORK", target:"WARWICK"},
    {source:"WARWICK", target:"YORK"},
    {source:"YORK", target:"WARWICK"},
    {source:"WARWICK", target:"CLIFFORD"},
    {source:"CLIFFORD", target:"YORK"},
    {source:"YORK", target:"CLIFFORD"},
    {source:"CLIFFORD", target:"YORK"},
    {source:"YORK", target:"CLIFFORD"},
    {source:"CLIFFORD", target:"YORK"},
    {source:"YORK", target:"CLIFFORD"},
    {source:"CLIFFORD", target:"YORK"},
    {source:"YORK", target:"YOUNG CLIFFORD"},
    {source:"YOUNG CLIFFORD", target:"RICHARD"},
    {source:"RICHARD", target:"QUEEN MARGARET"},
    {source:"QUEEN MARGARET", target:"KING HENRY VI"},
    {source:"KING HENRY VI", target:"QUEEN MARGARET"},
    {source:"QUEEN MARGARET", target:"YOUNG CLIFFORD"},
    {source:"YOUNG CLIFFORD", target:"YORK"},
    {source:"YORK", target:"RICHARD"},
    {source:"RICHARD", target:"SALISBURY"},
    {source:"SALISBURY", target:"YORK"},
    {source:"YORK", target:"WARWICK"},
    {source:"WARWICK", target:"YORK"}]
  };
// var myColor =d3.scaleOrdinal().domain(node)
// .range(["red","blue","red","blue","red","blue","red","blue","red","blue","red","blue","red","blue","red","blue"])

  var simulation = d3
    .forceSimulation(graph.nodes)
    .force(
      "link",
      d3
        .forceLink()
        .id(function(d) {
          return d.name;
        })
        .links(graph.links)
    )
    .force("gravity",gravity(-1000))
  

    .force("charge", d3.forceManyBody().strength(-500))
    .force("center", d3.forceCenter(width / 2, height / 2))
    .on("tick", ticked);

  var link = svg
    .append("g")
    .attr("class", "links")
    .selectAll("line")
    .data(graph.links)
    .enter()
    .append("line")
    .attr("stroke-width", function(d) {
      return 3;
    });
    var drag = 
      d3
        .drag()
        .on("start", dragstarted)
        .on("drag", dragged)
        .on("end", dragended);


var textandnode = svg
  .append("g")
  .selectAll("g")
  .data(graph.nodes)
  .enter()
  .append("g")
  .call(drag)
  ;

var circles = textandnode
.append("circle")
.attr("r", (d)=>d.size)
//.attr("r", "20")
//.attr("fill", function(d){
  //return color(d.group);
//})
.attr("fill", (d)=>d.color)
;

var texts = textandnode
.append("text")
.text(function(d){return d.name});

  // var node = svg
  //   .append("g")
  //   .attr("class", "nodes")
  //   .selectAll("circle")
  //   .data(graph.nodes)
  //   .enter()
  //   .append("circle")
  //   .attr("r", 10)
  //   .attr("fill", "red");

    // var drag = 
    //   d3
    //     .drag()
    //     .on("start", dragstarted)
    //     .on("drag", dragged)
    //     .on("end", dragended);
//node.call(drag);
  

 
  // nodes.append("text")
  // .text(function(d){
  //   return d.name;
  // })
  // .style("fill","#000")
  // .style("font-size", "20px")
  // .attr("x",6)
  // .attr("y",3);

// simulation.force(
//   'link',
//   d3.forceLink().id((link)=>link.id)
//   .strength((link)=>link.strength)
// );
// const linkElements = svg
// .append('g')
// .selectAll('line')
// .data(links)
// .enter()
// .append('line')
// .attr('stroke-width',1)
// .attr('stroke','#E5E5E5')
// .attr('x1',(link) => link.source.x)
// .attr('y1',(link) => link.source.y)
// .attr('x2',(link) => link.target.x)
// .attr('y2',(link) => link.target.y);

//simulation.force('link').link(links);
  function ticked() {
    textandnode.attr("transform", function(d){
      return "translate("+d.x+","+d.y+")";
    });
    link
      .attr("x1", function(d) {
        return d.source.x;
      })
      .attr("y1", function(d) {
        return d.source.y;
      })
      .attr("x2", function(d) {
        return d.target.x;
      })
      .attr("y2", function(d) {
        return d.target.y;
      });
    
  //   node
  //     .attr("cx", function(d) {
  //       return d.x;
  //     })
  //     .attr("cy", function(d) {
  //       return d.y;
  //     });
  // 
}

  function dragstarted(d) {
    if (!d3.event.active) simulation.alphaTarget(0.3).restart();
    d.fx = d.x;
    d.fy = d.y;
  }

  function dragged(d) {
    d.fx = d3.event.x;
    d.fy = d3.event.y;
  }

  function dragended(d) {
    if (!d3.event.active) simulation.alphaTarget(0);
    d.fx = null;
    d.fy = null;
  }
 function gravity(alpha){
  return function(d){
    d.y+=(d.cy -d.y)*alpha;
    d.x +=(d.cx-d.x)*alpha;
  };
 }
 


